/**
 * Reference peptide library — generated from the clinic's research CSV by
 * scripts/gen_peptide_library.py. Layers timing, half-life, purpose
 * affinities, and stack-interaction notes on top of the catalog products.
 *
 * Do not edit by hand; re-run the script to regenerate.
 */
import type { PeptideLibraryEntry } from '@beacon/domain';

export const peptideLibrary: PeptideLibraryEntry[] = [
  {
    productId: 'prod_5amino1mq',
    name: '5-Amino-1MQ',
    timingGuidance: 'Best administered in the morning or early afternoon to avoid sleep interference; rotate injection sites.',
    halfLifeHours: 3,
    purposeTags: ['Weight Loss', 'Anti-Aging', 'Metabolic Health'],
    purposeWeights: { brain_mood: 15, health_wellness: 65, beauty_antiaging: 20, weight_metabolic: 85, performance_muscle: 60, recovery_longevity: 55 },
    interactions: [
      { withName: 'NAD+ Precursors (NMN, NR)', compatibility: 'complementary', description: 'Has prospective to synergize by attenuating NAD+ breakdown while underpinning biosynthesis.' },
      { withName: 'Resveratrol', compatibility: 'complementary', description: 'When these are paired, underpins sirtuin bioactivity while 1MQ heightens NAD+ substrate.' },
      { withName: 'Carnitine', compatibility: 'complementary', description: 'Carnitine supports mitochondrial fat oxidation, which may be enhanced by 5-Amino-1MQ\'s effects on NNMT inhibition.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established interactions; prospectively reciprocally favorable biological routes.' },
      { withName: 'Blood Thinners', compatibility: 'neutral', description: 'Limited data; consult healthcare provider. This has implications for protocol design.' },
      { withName: 'Metformin', compatibility: 'incompatible', description: 'Research supports that each of these compounds modulate metabolic cascades; impacts has prospective to compound; monitor usage.' },
      { withName: 'Berberine', compatibility: 'incompatible', description: 'Prospective additive impacts on glucose metabolism; monitor dual protocol.' },
    ],
  },
  {
    productId: 'prod_ahkcu',
    name: 'AHK-Cu',
    timingGuidance: 'Apply to clean, dry scalp or skin. Evening application is preferred to avoid UV exposure which can degrade the peptide. If using other actives, apply AHK-Cu first and allow to absorb before layering.',
    halfLifeHours: 0.05,
    purposeTags: ['Hair Growth', 'Anti-Aging', 'Skin Quality'],
    purposeWeights: { brain_mood: 15, health_wellness: 70, beauty_antiaging: 85, weight_metabolic: 5, performance_muscle: 15, recovery_longevity: 75 },
    interactions: [
      { withName: 'GHK-Cu', withProductId: 'prod_ghkcu', compatibility: 'complementary', description: 'GHK-Cu excels at dermal restoration while AHK-Cu targets hair follicles. Reciprocally beneficial copper peptides targeting disparate aspects of histological regeneration. Clinical relevance is noteworthy. Is capable of be co-administered in formulations.' },
      { withName: 'Minoxidil', compatibility: 'complementary', description: 'In many cases co-administered in hair loss protocols Each of these compounds promote hair proliferative via disparate biological routes - minoxidil via potassium channel opening and vasodilation, AHK-Cu via dermal papilla stimulation and VEGF.' },
      { withName: 'Finasteride / Dutasteride', compatibility: 'complementary', description: 'Notably, disparate biological routes backing dual protocol approach 5-alpha reductase inhibitors block DHT production while AHK-Cu has prospective to serve to counter DHT impacts on follicles.' },
      { withName: 'Hyaluronic Acid', compatibility: 'complementary', description: 'Hyaluronic acid confers hydration and underpins peptide penetration while ahk-cu drives follicle and dermal health; excellent dual protocol.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Disparate histological restoration biological routes - BPC-157 drives systemic recuperative while AHK-Cu targets dermal/hair. Safe to harness in parallel for comprehensive regeneration backing.' },
      { withName: 'Vitamin C (L-Ascorbic Acid)', compatibility: 'neutral', description: 'Minimal pH of ascorbic acid is capable of destabilize copper peptides. Harness at disparate times - Vitamin C in morning, AHK-Cu in evening - to steer clear of interaction.' },
      { withName: 'Copper Supplements', compatibility: 'incompatible', description: 'Concern of copper toxicity when co-administered with additional copper sources. Monitor total copper intake and steer clear of stacking copper peptides with oral copper supplements.' },
      { withName: 'AHA/BHA Acids', compatibility: 'incompatible', description: 'Harness at disparate times or in separate routines Acidic exfoliants (glycolic, salicylic acid) is capable of destabilize copper peptide complexes and reduce effectiveness.' },
      { withName: 'Retinol / Retinoids', compatibility: 'incompatible', description: 'Introduce slowly or harness at disparate times to steer clear of sensitization Each of these compounds are potent actives that is capable of cause irritation. Retinoids likewise lower dermal pH.' },
      { withName: 'Iron Chelators', compatibility: 'incompatible', description: 'Has potential to interfere with copper binding and reduce peptide effectiveness. Monitor for attenuated efficacy if harnessing iron-chelating compounds. This has implications for protocol design.' },
    ],
  },
  {
    productId: 'prod_aod9604',
    name: 'AOD-9604',
    timingGuidance: 'Best administered in the morning on an empty stomach. Wait 30 minutes before eating. Some research protocols suggest injection into abdominal subcutaneous fat for localized effect.',
    halfLifeHours: 0.75,
    purposeTags: ['Weight Loss', 'Joint Health'],
    purposeWeights: { brain_mood: 10, health_wellness: 70, beauty_antiaging: 20, weight_metabolic: 85, performance_muscle: 40, recovery_longevity: 55 },
    interactions: [
      { withName: 'Hyaluronic Acid', compatibility: 'complementary', description: 'Research reveals co-administered AOD-9604 and HA injections are more potent for cartilage restoration than either alone.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Disparate biological routes of action. Individual variation should be considered. Sometimes co-administered in regenerative protocols.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'compatible', description: 'In terms of co-administration, aOD-9604 does not modulate GH axis, allowing dual protocol with GH secretagogues.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'compatible', description: 'No established interactions. Disparate biological routes - is capable of be used in tandem. Individual variation should be considered.' },
      { withName: 'Semaglutide', withProductId: 'prod_semaglutide', compatibility: 'compatible', description: 'Has prospective to have reciprocally beneficial impacts on weight management. Disparate adipose loss biological routes. Clinical relevance is noteworthy.' },
      { withName: 'Insulin', compatibility: 'compatible', description: 'AOD-9604 does not modulate glucose metabolism or insulin sensitivity unlike full hGH.' },
      { withName: 'Carnitine', compatibility: 'compatible', description: 'Carnitine facilitates fatty acid transport into mitochondria, supporting the lipolytic actions of AOD-9604.' },
    ],
  },
  {
    productId: 'prod_bpc157',
    name: 'BPC-157',
    timingGuidance: 'Injectable BPC-157 is most effective on empty stomach. For injury healing, inject as close to the injury site as possible (subcutaneous). Rotate injection sites to prevent tissue irritation.',
    halfLifeHours: 4,
    purposeTags: ['Tissue Repair', 'Digestive Health', 'Neurological Support'],
    purposeWeights: { brain_mood: 30, health_wellness: 85, beauty_antiaging: 40, weight_metabolic: 15, performance_muscle: 65, recovery_longevity: 90 },
    interactions: [
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'Reciprocally beneficial recuperative biological routes, in many cases used in tandem.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'BPC-157 heightens GH binding site expression, amplifying Ipamorelin\'s proliferative endocrine signal merits.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'BPC-157 upregulates GH binding sites, enhancing CJC-1295 effectiveness for histological restoration.' },
      { withName: 'GHRP-6', compatibility: 'compatible', description: 'Notably, no established unfavorable interactions.' },
      { withName: 'Melanotan II', withProductId: 'prod_melanotan2', compatibility: 'compatible', description: 'Disparate biological routes of action and binding site targets; no established interactions.' },
      { withName: 'AOD-9604', withProductId: 'prod_aod9604', compatibility: 'compatible', description: 'No cascade overlap. Individual variation should be considered. Safe dual protocol - BPC-157 promotes histological repair via proliferative factors, AOD-9604 targets fat metabolism via beta-3 adrenergic binding sites. In many cases combined in regenerative protocols.' },
    ],
  },
  {
    productId: 'prod_cagrilintide',
    name: 'Cagrilintide',
    timingGuidance: 'Administer same day each week. Evening injection may reduce morning nausea. Can be given with or without food due to subcutaneous route.',
    halfLifeHours: 168,
    purposeTags: ['Weight Loss', 'Appetite Suppression', 'Metabolic Health'],
    purposeWeights: { brain_mood: 30, health_wellness: 80, beauty_antiaging: 25, weight_metabolic: 85, performance_muscle: 35, recovery_longevity: 65 },
    interactions: [
      { withName: 'Semaglutide', withProductId: 'prod_semaglutide', compatibility: 'complementary', description: 'In terms of co-administration, cagriSema dual protocol exhibits amplified weight loss (22.7% vs 16.1% semaglutide alone) and bolstered glycemic control through reciprocally favorable GLP-1 and amylin cascades.' },
      { withName: 'Tirzepatide', withProductId: 'prod_tirzepatide', compatibility: 'compatible', description: 'No established direct interactions. Each of these compounds are potent weight loss agents with disparate biological routes - cagrilintide targets amylin/calcitonin binding sites while tirzepatide targets GLP-1/GIP binding sites.' },
      { withName: 'Liraglutide', compatibility: 'compatible', description: 'Each of these compounds GLP-1 agonists and amylin analogs operate by means of distinct satiety cascades. Phase 2 trials reveal analogous efficacy profiles with no adverse interactions.' },
      { withName: 'Metformin', compatibility: 'compatible', description: 'Favorably received dual protocol exhibited in Phase 2/3 trials. Timing of administration may matter. No pharmacokinetic interactions witnessed between cagrilintide and metformin. Individual variation should be considered.' },
      { withName: 'SGLT2 Inhibitors', compatibility: 'compatible', description: 'Each of these compounds biological routes complement each other for diabetes, in addition to weight management. Medical trials included patients on SGLT2 inhibitors with no safety concerns.' },
      { withName: 'Oral Contraceptives', compatibility: 'neutral', description: 'Delayed gastric emptying has potential to modulate absorption of oral contraceptives. From a mechanistic perspective, space administration by 1 hour before cagrilintide injection.' },
      { withName: 'Retatrutide', withProductId: 'prod_retatrutide', compatibility: 'incompatible', description: 'Each of these compounds cause pronounced GI impacts (gastroparesis, nausea). Cagrilintide (amylin agonist) and Retatrutide (triple GLP-1/GIP/glucagon agonist) have disparate biological routes that said compounded GI side impacts create substantial concern. Not suggested absent specialist supervision.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Monitor glucose concentrations closely as cagrilintide modulates gastric emptying and has potential to alter insulin absorption timing. Has potential to mandate insulin dose adjustments in diabetic patients.' },
      { withName: 'Pramlintide', compatibility: 'incompatible', description: 'Dual protocol would confer no additional merit and has potential to boost concern of gastrointestinal side impacts. Each of these compounds are amylin receptor agonists with overlapping biological routes. This has implications for protocol design.' },
    ],
  },
  {
    productId: 'prod_cjc1295_dac',
    name: 'CJC-1295 with DAC',
    timingGuidance: 'Due to long half-life, injection timing is flexible. Many prefer morning injections to monitor for side effects during the day.',
    halfLifeHours: 168,
    purposeTags: ['Growth Hormone', 'Recovery', 'Anti-Aging'],
    purposeWeights: { brain_mood: 25, health_wellness: 70, beauty_antiaging: 60, weight_metabolic: 60, performance_muscle: 85, recovery_longevity: 80 },
    interactions: [
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'incompatible', description: 'Evidence indicates that is capable of be co-administered that said continuous GH elevation from DAC version has potential to reduce mutually potentiating merits of pulsatile protocols.' },
      { withName: 'GHRP-6', compatibility: 'incompatible', description: 'GHRP pulse impacts are diminished when co-administered with continuous GH elevation from CJC-1295 DAC.' },
      { withName: 'MK-677', withProductId: 'prod_mk677', compatibility: 'incompatible', description: 'Each of these compounds confer continuous GH elevation - dual protocol has potential to lead to excessive and unnatural GH concentrations.' },
      { withName: 'Tesamorelin', withProductId: 'prod_tesamorelin', compatibility: 'incompatible', description: 'No additional merit and prospective binding site competition; each of these compounds are ghrh analogs.' },
      { withName: 'HGH', withProductId: 'prod_hgh', compatibility: 'incompatible', description: 'Co-administering with exogenous HGH defeats the purpose and has prospective to suppress natural biosynthesis.' },
      { withName: 'Sermorelin', withProductId: 'prod_sermorelin', compatibility: 'incompatible', description: 'Each of these compounds operate by means of GHRH cascade - CJC-1295 DAC is already more potent, alongside long-lasting.' },
    ],
  },
  {
    productId: 'prod_cjc_ipa',
    name: 'CJC-1295 / Ipamorelin',
    timingGuidance: 'Administer 30+ minutes away from food for optimal absorption. Morning dose upon waking, evening dose before bed for best results.',
    halfLifeHours: 0.5,
    purposeTags: ['Growth Hormone', 'Recovery', 'Anti-Aging'],
    purposeWeights: { brain_mood: 25, health_wellness: 65, beauty_antiaging: 55, weight_metabolic: 55, performance_muscle: 80, recovery_longevity: 75 },
    interactions: [
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'Excellent dual protocol - Ipamorelin (GHRP) + CJC-1295 (GHRH) confers reciprocally beneficial GH secretion by means of disparate binding site cascades.' },
      { withName: 'GHRP-6', compatibility: 'complementary', description: 'Potent synergy when co-administered - GHRP-6 amplifies the GH pulse initiated by CJC-1295.' },
      { withName: 'GHRP-2', compatibility: 'complementary', description: 'Potent dual protocol for maximizing proliferative endocrine signal secretion by means of dual cascade activation. Timing of administration may matter.' },
      { withName: 'MK-677', withProductId: 'prod_mk677', compatibility: 'compatible', description: 'Research supports that disparate biological routes - MK-677 confers continuous ghrelin stimulation while CJC-1295 yields pulsatile GHRH.' },
      { withName: 'Hexarelin', compatibility: 'incompatible', description: 'Is capable of be co-administered that said monitor for excessive GH elevation due to Hexarelin\'s potency.' },
      { withName: 'CJC-1295 with DAC', withProductId: 'prod_cjc1295_dac', compatibility: 'incompatible', description: 'Choose one based on desired secretion pattern; steer clear of co-administering disparate cjc-1295 variants.' },
      { withName: 'Tesamorelin', withProductId: 'prod_tesamorelin', compatibility: 'incompatible', description: 'Each of these compounds are GHRH analogs - co-administering confers no additional merit and has prospective to cause binding site competition.' },
    ],
  },
  {
    productId: 'prod_dihexa',
    name: 'Dihexa',
    timingGuidance: 'Morning, with or without food',
    halfLifeHours: null,
    purposeTags: ['Cognitive Health', 'Neurological Support'],
    purposeWeights: { brain_mood: 90, health_wellness: 55, beauty_antiaging: 20, weight_metabolic: 0, performance_muscle: 10, recovery_longevity: 60 },
    interactions: [
      { withName: 'Semax', withProductId: 'prod_semax', compatibility: 'compatible', description: 'Is capable of be stacked for enhanced cognitive merits that said calls for prudent cycling to steer clear of overstimulation.' },
      { withName: 'Selank', withProductId: 'prod_selank', compatibility: 'compatible', description: 'That said monitor for neural overstimulation, mutually potentiating cognitive and anxiolytic impacts when co-administered.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established unfavorable interactions - disparate biological routes of action.' },
      { withName: 'Noopept', compatibility: 'compatible', description: 'Evidence indicates that some users stack for cognitive enhancement that said limited safety data on dual protocol.' },
      { withName: 'NAD+', withProductId: 'prod_nad', compatibility: 'compatible', description: 'Reciprocally favorable biological routes - NAD+ underpins cell-based bioenergetic while Dihexa drives synaptogenesis.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'compatible', description: 'No established interactions - TB-500 focuses on histological restoration while Dihexa targets neural connections.' },
      { withName: 'P21', compatibility: 'incompatible', description: 'Steer clear of concurrent harness absent prudent cycling; each of these compounds modulate neuroplasticity strongly.' },
      { withName: 'Cerebrolysin', compatibility: 'incompatible', description: 'Each of these compounds are potent neurotrophic agents - co-administering has potential to lead to excessive stimulation.' },
    ],
  },
  {
    productId: 'prod_dsip',
    name: 'DSIP',
    timingGuidance: 'Not specified',
    halfLifeHours: 0.33,
    purposeTags: ['Sleep Quality', 'Emotional Support', 'Metabolic Health'],
    purposeWeights: { brain_mood: 65, health_wellness: 70, beauty_antiaging: 40, weight_metabolic: 20, performance_muscle: 35, recovery_longevity: 75 },
    interactions: [
      { withName: 'Melatonin', compatibility: 'complementary', description: 'Dsip amplifies measured-wave sleep while melatonin regulates circadian rhythm, creating reciprocally beneficial sleep merits; each of these compounds govern sleep-wake cycles.' },
      { withName: 'Selank', withProductId: 'prod_selank', compatibility: 'complementary', description: 'Research supports that reciprocally beneficial anxiolytic impacts - Selank attenuates anxiety while DSIP bolsters sleep and stress response.' },
      { withName: 'Epitalon', withProductId: 'prod_epitalon', compatibility: 'complementary', description: 'Epitalon amplifies melatonin biosynthesis while dsip bolsters sleep quality; each of these compounds backing circadian regulation.' },
      { withName: 'Cortisol Modulators', compatibility: 'compatible', description: 'DSIP serves to govern cortisol - is capable of be used alongside adaptogenic compounds for comprehensive stress management.' },
      { withName: 'Semax', withProductId: 'prod_semax', compatibility: 'compatible', description: 'Disparate biological routes - Semax for daytime cognition, DSIP for nighttime recovery, creating 24-hour optimization.' },
      { withName: 'Growth Hormone Peptides', compatibility: 'compatible', description: 'From a mechanistic perspective, no direct interaction - DSIP has prospective to backing natural GH secretion during sleep absent interfering with GH peptides.' },
      { withName: 'GABA Agonists', compatibility: 'incompatible', description: 'Monitor for excessive sedation when co-administering with benzodiazepines or other gaba modulators; dsip amplifies gaba bioactivity.' },
      { withName: 'Opioid Medications', compatibility: 'incompatible', description: 'Professional supervision required with opioid medications; dsip has potential to modulate opioid binding sites and has been used in withdrawal.' },
    ],
  },
  {
    productId: 'prod_epitalon',
    name: 'Epitalon',
    timingGuidance: 'Morning dose 30 minutes before breakfast',
    halfLifeHours: 0.05,
    purposeTags: ['Immune System', 'Anti-Aging', 'Neurological Support'],
    purposeWeights: { brain_mood: 45, health_wellness: 90, beauty_antiaging: 70, weight_metabolic: 30, performance_muscle: 35, recovery_longevity: 100 },
    interactions: [
      { withName: 'Melatonin', compatibility: 'complementary', description: 'Each of these compounds operate by means of pineal cascades - Epitalon heightens endogenous melatonin biosynthesis, creating reciprocally beneficial circadian and anti-aging impacts.' },
      { withName: 'Thymalin', compatibility: 'complementary', description: 'Co-administered harness in Russian protocols reveals amplified immunomodulation and geroprotective impacts by means of reciprocally beneficial biological routes.' },
      { withName: 'NAD+ Precursors', compatibility: 'compatible', description: 'Operate by means of disparate anti-aging cascades (telomerase vs nad+ metabolism); no direct interaction.' },
      { withName: 'Growth Hormone Peptides', compatibility: 'compatible', description: 'No established interactions - Epitalon operates by means of telomerase/pineal cascades while GH peptides harness pituitary axis.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Disparate biological routes - is capable of be used in tandem safely for comprehensive regenerative backing.' },
      { withName: 'Semax/Selank', compatibility: 'compatible', description: 'No direct interactions - Epitalon focuses on cell-based aging while these target neurocognitive role. Clinical relevance is noteworthy.' },
      { withName: 'Cancer Therapeutics', compatibility: 'neutral', description: 'Notably, telomerase activation in cancer context calls for prudent consideration - consult oncologist before harness.' },
      { withName: 'Cortexin', compatibility: 'incompatible', description: 'Monitor for amplified cognitive impacts and adjust dosing if needed; each of these compounds have neuroprotective impacts.' },
    ],
  },
  {
    productId: 'prod_ghkcu',
    name: 'GHK-Cu',
    timingGuidance: 'Apply GHK-Cu topically to clean, dry skin. Morning use requires sunscreen. Evening application allows for overnight repair. Start with once daily to assess tolerance.',
    halfLifeHours: 0.05,
    purposeTags: ['Skin Quality', 'Hair Growth', 'Anti-Inflammatory'],
    purposeWeights: { brain_mood: 15, health_wellness: 80, beauty_antiaging: 100, weight_metabolic: 10, performance_muscle: 25, recovery_longevity: 85 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'Amplified wound recuperative and histological restoration when used in tandem.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'Disparate recuperative cascades that operate well in dual protocol. This has implications for protocol design.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'compatible', description: 'In terms of co-administration, proliferative endocrine signal impacts has prospective to complement collagen synthesis.' },
      { withName: 'Melanotan II', withProductId: 'prod_melanotan2', compatibility: 'incompatible', description: 'Each of these compounds modulate melanin biosynthesis, monitor for dermal discoloration. Individual variation should be considered.' },
      { withName: 'Copper Supplements', compatibility: 'incompatible', description: 'Concern of copper toxicity when co-administered with additional copper sources.' },
      { withName: 'Iron Chelators', compatibility: 'incompatible', description: 'Has prospective to interfere with copper binding and peptide effectiveness.' },
    ],
  },
  {
    productId: 'prod_glutathione',
    name: 'Glutathione',
    timingGuidance: 'Glutathione can be administered at any time of day. IV infusions are typically given in clinical settings. For home IM/SubQ injections, consistency in timing is more important than specific time of day.',
    halfLifeHours: 0.1,
    purposeTags: ['Immune System', 'Oxidative Balance', 'Cellular Detox'],
    purposeWeights: { brain_mood: 40, health_wellness: 90, beauty_antiaging: 75, weight_metabolic: 40, performance_muscle: 30, recovery_longevity: 85 },
    interactions: [],
  },
  {
    productId: 'prod_hgh',
    name: 'HGH',
    timingGuidance: 'Morning fasted injection maximizes fat-burning potential. Evening injection mimics natural nocturnal GH pulse. At doses >4 IU, splitting into AM and PM injections can reduce side effects and improve utilization.',
    halfLifeHours: 3.5,
    purposeTags: ['Growth Hormone', 'Anti-Aging', 'Muscle Development'],
    purposeWeights: { brain_mood: 30, health_wellness: 75, beauty_antiaging: 80, weight_metabolic: 70, performance_muscle: 100, recovery_longevity: 90 },
    interactions: [
      { withName: 'IGF-1 / IGF-1 LR3', compatibility: 'complementary', description: 'HGH stimulates endogenous IGF-1 biosynthesis. Adding exogenous IGF-1 compounds impacts that said heightens hypoglycemia, alongside side impact concerns.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'Is capable of be used with HGH for amplified impacts, though has potential to be redundant if harnessing adequate HGH doses GHRH analog that stimulates natural GH secretion. Clinical relevance is noteworthy.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'Dual protocol has potential to enhance overall GH/IGF-1 axis however heightens complexity. Clinical relevance is noteworthy. In terms of co-administration, ghrelin mimetic that stimulates GH secretion via disparate cascade.' },
      { withName: 'GHRP-6 / GHRP-2', compatibility: 'complementary', description: 'Is capable of enhance natural pulsatile secretion alongside exogenous administration When these are paired, proliferative endocrine signal releasing peptides operate synergistically with HGH.' },
      { withName: 'Testosterone', compatibility: 'complementary', description: 'When these are paired, each of these compounds backing anabolism, body composition, and well-being. Monitor estrogen conversion Routinely co-administered in endocrine signal replacement protocols.' },
      { withName: 'Semaglutide / Tirzepatide', compatibility: 'complementary', description: 'Increasingly co-administered in body composition protocols. Timing of administration may matter. GLP-1 agonists has potential to serve to manage HGH-induced insulin resistance while underpinning adipose loss goals. This has implications for protocol design.' },
      { withName: 'Zinc', compatibility: 'compatible', description: 'Zinc supports IGF-1 function and testosterone levels, which interact with growth hormone pathways.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'HGH decreases insulin sensitivity and is capable of cause insulin resistance. Diabetics has prospective to need heightened insulin doses. Monitor circulatory glucose closely when co-administering.' },
      { withName: 'Thyroid Hormones (T3/T4)', compatibility: 'incompatible', description: 'HGH heightens T4 to T3 conversion and is capable of unmask central hypothyroidism in 36-47% of patients. Monitor thyroid role; has potential to mandate T4 supplementation. This has implications for protocol design.' },
      { withName: 'Cortisol / Hydrocortisone', compatibility: 'incompatible', description: 'HGH is capable of unmask cortisol deficiency in hypopituitary patients. Cortisol replacement should precede HGH therapy in patients with multiple deficiencies. Clinical relevance is noteworthy.' },
      { withName: 'Metformin', compatibility: 'incompatible', description: 'Some evidence points to metformin has potential to reduce IGF-1 concentrations - monitor response. Timing of administration may matter. Metformin has potential to be used to manage HGH-induced insulin resistance.' },
    ],
  },
  {
    productId: 'prod_igf1lr3',
    name: 'IGF-1 LR3',
    timingGuidance: 'Post-workout window critical for safety and efficacy. IGF-1 receptors most sensitive when muscles depleted. Must consume carbohydrates immediately to prevent dangerous hypoglycemia lasting up to 30 hours.',
    halfLifeHours: 25,
    purposeTags: ['Muscle Development', 'Metabolic Health', 'Tissue Repair'],
    purposeWeights: { brain_mood: 20, health_wellness: 65, beauty_antiaging: 60, weight_metabolic: 40, performance_muscle: 100, recovery_longevity: 85 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'BPC-157 (250-500mcg 2x daily) with IGF-1 LR3 (40-60mcg daily) has potential to accelerate histological restoration. Popular recuperative stack.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'TB-500 (2-5mg weekly) with IGF-1 LR3 amplifies recovery by means of disparate cascades. Reciprocally beneficial recuperative biological routes.' },
      { withName: 'Protein', compatibility: 'compatible', description: 'Adequate protein intake provides amino acid substrates necessary for the anabolic effects promoted by IGF-1 signaling.' },
      { withName: 'Metformin', compatibility: 'neutral', description: 'Has prospective to serve to mitigate insulin resistance from chronic IGF-1 harness, that said calls for circulatory glucose monitoring and dose adjustment.' },
      { withName: 'Human Growth Hormone', compatibility: 'incompatible', description: 'HGH already elevates endogenous IGF-1, adding exogenous LR3 amplifies cancer concern and organ hypertrophy. Clinical relevance is noteworthy. Creates excessive IGF-1 concentrations. Clinical relevance is noteworthy.' },
      { withName: 'CJC-1295/Ipamorelin', withProductId: 'prod_cjc_ipa', compatibility: 'incompatible', description: 'Each of these compounds trigger GH/IGF-1 axis. Co-administered harness has prospective to cause binding site desensitization and compounded metabolic impacts.' },
      { withName: 'MK-677', withProductId: 'prod_mk677', compatibility: 'incompatible', description: 'Research supports that monitor for joint pain, water retention, and insulin sensitivity disruption. MK-677 heightens endogenous IGF-1.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Mutually potentiating hypoglycemic impacts is capable of be life-threatening. Calls for professional medical supervision if co-administered. Timing of administration may matter.' },
      { withName: 'Anabolic Steroids', compatibility: 'incompatible', description: 'Amplified anabolic impacts however substantially heightened health concerns including organ hypertrophy and metabolic dysfunction.' },
      { withName: 'Cerebrolysin', compatibility: 'incompatible', description: 'Each of these compounds modulate proliferative factor cascades, together with neuroplasticity. IGF-1 LR3 binds IGF-1 receptors while Cerebrolysin amplifies BDNF/NGF. Prospective for additive neurotrophic impacts - harness conservative doses, in addition to monitor for signs of excessive stimulation.' },
    ],
  },
  {
    productId: 'prod_ipamorelin',
    name: 'Ipamorelin',
    timingGuidance: 'Injectable Ipamorelin is most effective on an empty stomach. For sleep benefits, inject 30 minutes before bed. For body composition, consider morning fasted injection or pre-workout timing for enhanced fat oxidation.',
    halfLifeHours: 2,
    purposeTags: ['Growth Hormone', 'Recovery', 'Muscle Development'],
    purposeWeights: { brain_mood: 20, health_wellness: 65, beauty_antiaging: 55, weight_metabolic: 55, performance_muscle: 80, recovery_longevity: 75 },
    interactions: [
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'Gold standard dual protocol - CJC extends GH secretion while Ipamorelin confers the pulse for peak proliferative endocrine signal cycles.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'BPC-157 upregulates GH binding sites, prospectively enhancing Ipamorelin effectiveness for recovery and muscular proliferative.' },
      { withName: 'Arginine', compatibility: 'complementary', description: 'Arginine can potentiate growth hormone release when combined with GHRP peptides like Ipamorelin.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'compatible', description: 'Reciprocally favorable for muscular recovery, histological restoration, and overall regeneration.' },
      { withName: 'Sermorelin', withProductId: 'prod_sermorelin', compatibility: 'incompatible', description: 'Each of these compounds trigger GH secretion, choose one to steer clear of binding site oversaturation.' },
      { withName: 'GHRP-2', compatibility: 'incompatible', description: 'Redundant GH stimulation cascades, has potential to cause binding site desensitization.' },
      { withName: 'GHRP-6', compatibility: 'incompatible', description: 'Analogous biological route with higher hunger impacts, stick to Ipamorelin for cleaner profile.' },
      { withName: 'Tesamorelin', withProductId: 'prod_tesamorelin', compatibility: 'incompatible', description: 'Mutually potentiating GH stimulation possible. Individual variation should be considered. Monitor IGF-1 concentrations closely and consider dose adjustments to prevent excessive proliferative endocrine signal elevation.' },
    ],
  },
  {
    productId: 'prod_kpv',
    name: 'KPV',
    timingGuidance: 'KPV can be dosed flexibly. For gut issues, some prefer morning dosing. For systemic inflammation, split doses may provide better coverage.',
    halfLifeHours: 0.05,
    purposeTags: ['Gut Support', 'Anti-Inflammatory', 'Immune System'],
    purposeWeights: { brain_mood: 20, health_wellness: 90, beauty_antiaging: 35, weight_metabolic: 15, performance_muscle: 20, recovery_longevity: 75 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'Reciprocally beneficial gastrointestinal recuperative biological routes - BPC-157 drives histological restoration while KPV attenuates inflammatory response.' },
      { withName: 'LL-37', withProductId: 'prod_ll37', compatibility: 'complementary', description: 'Kpv focuses on inflammation-related response while ll-37 on direct antimicrobial action; each of these compounds are antimicrobial peptides.' },
      { withName: 'GHK-Cu', withProductId: 'prod_ghkcu', compatibility: 'complementary', description: 'Excellent dual protocol for dermal health - GHK-Cu drives collagen while KPV attenuates inflammation-related response. Individual variation should be considered.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'compatible', description: 'Has potential to work well in tandem; both have anti-inflammatory response-related properties by means of disparate pathways.' },
      { withName: 'Thymosin Alpha-1', withProductId: 'prod_thymosin_a1', compatibility: 'compatible', description: 'Disparate immunological modulation biological routes - TA1 amplifies immunological role while KPV attenuates inflammation-related response.' },
      { withName: 'Probiotics', compatibility: 'compatible', description: 'Probiotics support gut microbiome health while KPV addresses inflammatory signaling, offering a comprehensive approach to gut wellness.' },
      { withName: 'Melanotan II', withProductId: 'prod_melanotan2', compatibility: 'incompatible', description: 'KPV is derived from α-MSH like MT-II that said absent tanning impacts - harnessing each of these compounds is unnecessary.' },
    ],
  },
  {
    productId: 'prod_ll37',
    name: 'LL-37',
    timingGuidance: 'Evening administration may optimize natural circadian immune function. Can be taken with or without food as absorption is independent of meals.',
    halfLifeHours: 5,
    purposeTags: ['Recovery', 'Tissue Repair', 'Immune System'],
    purposeWeights: { brain_mood: 10, health_wellness: 85, beauty_antiaging: 35, weight_metabolic: 10, performance_muscle: 20, recovery_longevity: 70 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'In terms of co-administration, amplified wound healing and histological repair through reciprocally favorable biological routes - LL-37 confers antimicrobial protection while BPC-157 accelerates histological regeneration.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'Co-administered anti-inflammation-related and recuperative impacts with LL-37 conferring antimicrobial bioactivity and TB-500 enhancing cell-based migration and angiogenesis.' },
      { withName: 'Conventional Antibiotics', compatibility: 'complementary', description: 'Notably, lL-37 exhibits mutually potentiating impacts with chloramphenicol, ciprofloxacin, and oxacillin against multidrug-resistant bacteria, with FICI values 0.25-0.5.' },
      { withName: 'Vitamin D3', compatibility: 'complementary', description: 'Vitamin D3 acts as cofactor for VDR to induce endogenous LL-37 biosynthesis, enhancing innate immunological responses, coupled with antimicrobial bioactivity.' },
      { withName: 'Lactoferrin', compatibility: 'compatible', description: 'Each of these compounds antimicrobial peptides is capable of be used in tandem safely with no documented unfavorable interactions in wound recuperative applications.' },
      { withName: 'Novel Synthetic AMPs', compatibility: 'neutral', description: 'Medical interaction profile not established for most dual protocols. Limited data on interactions with other synthetic antimicrobial peptides.' },
      { withName: 'Physiological Salt Solutions', compatibility: 'incompatible', description: 'Consider dosing adjustments in substantial-salt conditions. Substantial salt concentrations in biological environments is capable of reduce LL-37 antimicrobial bioactivity. Clinical relevance is noteworthy.' },
      { withName: 'Amino Acid Solutions', compatibility: 'incompatible', description: 'From a mechanistic perspective, steer clear of co-administration in same solution. Research supports that physical incompatibility has potential to occur with certain residue solutions, notably in IV formulations.' },
    ],
  },
  {
    productId: 'prod_melanotan1',
    name: 'Melanotan I',
    timingGuidance: 'Multiple daily injections needed due to 30-minute half-life. Best results when combined with minimal UV exposure 2-3 hours after injection for enhanced melanin synthesis.',
    halfLifeHours: 0.5,
    purposeTags: ['Skin Quality', 'Anti-Aging', 'Dermal Protection'],
    purposeWeights: { brain_mood: 15, health_wellness: 40, beauty_antiaging: 80, weight_metabolic: 10, performance_muscle: 15, recovery_longevity: 25 },
    interactions: [
      { withName: 'UV Exposure', compatibility: 'complementary', description: 'In terms of co-administration, melanotan I amplifies tanning response to UV exposure, allowing deeper pigmentation with less sun exposure. Attenuates required UV dose for tanning by approximately 50%.' },
      { withName: 'Melanotan II', withProductId: 'prod_melanotan2', compatibility: 'compatible', description: 'Should not be co-administered due to overlapping biological routes, in addition to additive impacts. Each of these compounds target melanocortin binding sites however Melanotan I has better safety profile and selectivity for MC1R.' },
      { withName: 'Beta-Carotene', compatibility: 'compatible', description: 'Evidence indicates that natural carotenoid confers additional photoprotection. No established interactions with Melanotan I. Is capable of be used in tandem for amplified dermal protection.' },
      { withName: 'Self-Tanning Products', compatibility: 'compatible', description: 'Topical self-tanners operate by means of disparate biological routes (DHA) and is capable of be used alongside Melanotan I for amplified cosmetic appearance.' },
      { withName: 'Tretinoin/Retinoids', compatibility: 'incompatible', description: 'Retinoids boost dermal photosensitivity while Melanotan I confers photoprotection. Monitor for dermal reactions and adjust UV exposure accordingly.' },
      { withName: 'Photosensitizing Medications', compatibility: 'incompatible', description: 'Antibiotics, diuretics, and other photosensitizing drugs has potential to boost UV sensitivity. When these are paired, amplified monitoring suggested when co-administering with Melanotan I.' },
    ],
  },
  {
    productId: 'prod_melanotan2',
    name: 'Melanotan II',
    timingGuidance: 'For tanning: morning dosing preferred. For sexual effects: 2-4 hours before activity. Can split daily dose to minimize side effects.',
    halfLifeHours: 0.55,
    purposeTags: ['Skin Quality', 'Metabolic Health', 'Libido Support'],
    purposeWeights: { brain_mood: 25, health_wellness: 40, beauty_antiaging: 85, weight_metabolic: 15, performance_muscle: 20, recovery_longevity: 30 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established interactions - disparate biological routes of action and binding site targets.' },
      { withName: 'Growth Hormone Peptides', compatibility: 'compatible', description: 'No documented interactions - operate by means of disparate cascades (GHRH/ghrelin vs melanocortin).' },
      { withName: 'Sunscreen', compatibility: 'compatible', description: 'Sunscreen remains essential during MT-II use; the peptide enhances tanning response but does not replace UV protection.' },
      { withName: 'Thyroid Medications', compatibility: 'neutral', description: 'Evidence indicates that no specific studies on interaction - consult healthcare provider as each of these compounds is capable of modulate metabolism.' },
      { withName: 'PT-141 (Bremelanotide)', compatibility: 'incompatible', description: 'Each of these compounds act on melanocortin binding sites - co-administering has potential to cause excessive side impacts including nausea, coupled with circulatory pressure changes.' },
      { withName: 'Alpha-MSH', compatibility: 'incompatible', description: 'Redundant biological route - each of these compounds trigger same melanocortin binding sites, boosting concern of side impacts absent additional merit.' },
      { withName: 'Cialis/Viagra', compatibility: 'incompatible', description: 'Has prospective to enhance sexual impacts - monitor for prolonged erections and cardiovascular impacts, especially circulatory pressure.' },
      { withName: 'Blood Pressure Medications', compatibility: 'incompatible', description: 'Monitor closely if co-administering with antihypertensives; mt-ii is capable of modulate circulatory pressure.' },
      { withName: 'Appetite Suppressants', compatibility: 'incompatible', description: 'MT-II has appetite suppressing impacts - monitor for excessive appetite attenuation when co-administering. Clinical relevance is noteworthy.' },
    ],
  },
  {
    productId: 'prod_mk677',
    name: 'MK-677',
    timingGuidance: 'Take MK-677 at bedtime (around 10:40 PM) on empty stomach to align with natural growth hormone patterns and minimize daytime appetite stimulation. Wait 2+ hours after last meal for optimal absorption.',
    halfLifeHours: 5,
    purposeTags: ['Anti-Aging', 'Tissue Repair', 'Cellular Energy'],
    purposeWeights: { brain_mood: 25, health_wellness: 70, beauty_antiaging: 55, weight_metabolic: 60, performance_muscle: 85, recovery_longevity: 80 },
    interactions: [
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'Cjc-1295 confers pulsatile secretion while mk-677 maintains baseline elevation; reciprocally beneficial gh cascades.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'Each of these compounds trigger GH secretion by means of disparate biological routes, creating pharmaceutical-grade endocrine signal concentrations.' },
      { withName: 'GHRP-2', compatibility: 'complementary', description: 'MK-677\'s sustained baseline elevation combines with GHRP-2\'s strategic pulsatile spikes.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'compatible', description: 'Evidence indicates that mK-677 amplifies recovery and histological restoration impacts by means of systemic proliferative factor elevation.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Mk-677 confers systemic proliferative factors while bpc-157 yields localized recuperative; non-competing biological routes.' },
      { withName: 'HGH', withProductId: 'prod_hgh', compatibility: 'incompatible', description: 'Redundant impacts absent proportional merits - has prospective to boost side impact concern.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'MK-677 decreases insulin sensitivity - calls for prudent circulatory glucose monitoring with diabetes medications. Timing of administration may matter.' },
      { withName: 'LGD-4033', compatibility: 'incompatible', description: 'Case report reveals 85.7% testosterone suppression, together with 95.8% liver enzyme elevation when co-administered.' },
    ],
  },
  {
    productId: 'prod_motsc',
    name: 'MOTS-c',
    timingGuidance: 'Optimal timing is morning before exercise. Exercise enhances endogenous MOTS-c production by 11.9-fold in muscle tissue. AMPK activation occurs within 30 minutes of administration.',
    halfLifeHours: null,
    purposeTags: ['Physical Performance', 'Metabolic Health', 'Anti-Aging'],
    purposeWeights: { brain_mood: 30, health_wellness: 75, beauty_antiaging: 40, weight_metabolic: 80, performance_muscle: 75, recovery_longevity: 85 },
    interactions: [
      { withName: 'NAD+ Precursors', compatibility: 'complementary', description: 'Complementary mitochondrial enhancement by means of disparate cascades. Individual variation should be considered. Has prospective to amplify metabolic and anti-aging merits.' },
      { withName: 'Resveratrol', compatibility: 'complementary', description: 'Reciprocally favorable SIRT1/AMPK activation has potential to enhance longevity and metabolic merits.' },
      { withName: 'Growth Hormone Peptides', compatibility: 'compatible', description: 'Research supports that disparate biological routes allow safe dual protocol with prospective mutually potentiating metabolic merits.' },
      { withName: 'Metformin', compatibility: 'incompatible', description: 'Monitor circulatory glucose closely. Timing of administration may matter. Each of these compounds engage AMPK cascade - has potential to cause additive hypoglycemic impacts.' },
      { withName: 'Berberine', compatibility: 'incompatible', description: 'Each of these compounds are AMPK activators with prospective for additive glucose-lowering impacts.' },
      { withName: 'Diabetes Medications', compatibility: 'incompatible', description: 'From a mechanistic perspective, amplified insulin sensitivity has prospective to mandate dose adjustments to prevent hypoglycemia.' },
    ],
  },
  {
    productId: 'prod_nad',
    name: 'NAD+',
    timingGuidance: 'Evening application allows NAD+ to work during skin\'s natural repair cycle',
    halfLifeHours: 0.625,
    purposeTags: ['Cellular Energy', 'Anti-Aging', 'Neurological Support'],
    purposeWeights: { brain_mood: 55, health_wellness: 85, beauty_antiaging: 65, weight_metabolic: 70, performance_muscle: 50, recovery_longevity: 90 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'Co-administered protocols enhance cell-based restoration, alongside bioenergetic biosynthesis.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'Reciprocally beneficial impacts on histological regeneration and mitochondrial role. Timing of administration may matter.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'Proliferative endocrine signal cascades merit from bolstered cell-based bioenergetic metabolism.' },
      { withName: 'Tirzepatide', withProductId: 'prod_tirzepatide', compatibility: 'compatible', description: 'In terms of co-administration, nAD+ underpins metabolic cascades amplified by GLP-1 agonists.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'compatible', description: 'Amplified recovery and anti-aging impacts when co-administered.' },
      { withName: 'Alcohol', compatibility: 'incompatible', description: 'Alcohol consumption substantially attenuates NAD+ concentrations and effectiveness. Timing of administration may matter.' },
    ],
  },
  {
    productId: 'prod_pegmgf',
    name: 'PEG-MGF',
    timingGuidance: 'Post-workout administration may align with natural MGF upregulation patterns. For localized effects, inject bilaterally into or near target muscles.',
    halfLifeHours: 5,
    purposeTags: ['Recovery', 'Tissue Repair', 'Muscle Repair'],
    purposeWeights: { brain_mood: 10, health_wellness: 60, beauty_antiaging: 45, weight_metabolic: 30, performance_muscle: 95, recovery_longevity: 80 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'BPC-157 drives angiogenesis while PEG-MGF activates satellite cellular tissue. Popular recovery stack. Reciprocally beneficial recuperative biological routes.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'In terms of co-administration, tB-500 drives cell migration and attenuates inflammatory response while PEG-MGF activates muscular stem cell-based tissue. Routinely co-administered for injury recovery. Timing of administration may matter.' },
      { withName: 'Thymosin Beta-4', withProductId: 'prod_thymosin_b4', compatibility: 'complementary', description: 'Dual protocol has prospective to enhance histological restoration by means of multiple biological routes. TB-4 and PEG-MGF operate by means of disparate regenerative cascades. Clinical relevance is noteworthy.' },
      { withName: 'IGF-1 LR3', withProductId: 'prod_igf1lr3', compatibility: 'incompatible', description: 'If used in tandem, reduce doses of each substantially. Co-administering has prospective to cause binding site overstimulation. Research supports that each of these compounds target IGF-1 cascades.' },
      { withName: 'Human Growth Hormone', compatibility: 'incompatible', description: 'Notably, co-administered harness has potential to amplify impacts however likewise concerns. Monitor for excessive water retention and joint pain. Timing of administration may matter. HGH heightens endogenous IGF-1/MGF.' },
      { withName: 'CJC-1295/Ipamorelin', withProductId: 'prod_cjc_ipa', compatibility: 'incompatible', description: 'From a mechanistic perspective, has potential to enhance PEG-MGF impacts however monitor for mutually potentiating side impacts. GH secretagogues boost endogenous GH/IGF-1 axis bioactivity.' },
      { withName: 'MK-677', withProductId: 'prod_mk677', compatibility: 'incompatible', description: 'Combined harness has potential to provide additive proliferative impacts that said increases concern of binding site desensitization. MK-677 elevates IGF-1 concentrations chronically.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'In terms of co-administration, pEG-MGF has prospective to have insulin-like impacts. Each of these compounds modulate glucose metabolism. Monitor circulatory sugar prudently if co-administered.' },
    ],
  },
  {
    productId: 'prod_pinealon',
    name: 'Pinealon',
    timingGuidance: 'Morning injection aligns with natural circadian rhythms. Rotate injection sites.',
    halfLifeHours: 0.05,
    purposeTags: ['Cognitive Health', 'Anti-Aging', 'Neurological Support'],
    purposeWeights: { brain_mood: 60, health_wellness: 70, beauty_antiaging: 40, weight_metabolic: 10, performance_muscle: 10, recovery_longevity: 85 },
    interactions: [
      { withName: 'Epitalon', withProductId: 'prod_epitalon', compatibility: 'complementary', description: 'Notably, russian protocols combine each of these compounds for comprehensive longevity backing. Amplified neuroprotection and anti-aging impacts by means of reciprocally beneficial telomerase activation and DNA interaction cascades.' },
      { withName: 'Cortexin', compatibility: 'complementary', description: 'Pinealon confers DNA-concentration neuroprotection while Cortexin yields histological-concentration backing. Mutually potentiating cognitive recovery in stroke patients by means of reciprocally beneficial cerebral region targeting.' },
      { withName: 'Thymalin', compatibility: 'compatible', description: 'In terms of co-administration, long-term Russian protocols reveal 2.5-fold mortality attenuation when co-administered with Epithalamin. Safe dual protocol underpinning neural-immunological axis optimization.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Disparate biological routes with no established interactions. BPC-157 focuses on histological restoration while Pinealon targets neurological and aging cascades.' },
      { withName: 'NAD+', withProductId: 'prod_nad', compatibility: 'compatible', description: 'Reciprocally beneficial anti-aging biological routes. NAD+ underpins cell-based bioenergetic while Pinealon provides DNA-concentration protection and gene expression modulation.' },
      { withName: 'Melatonin', compatibility: 'incompatible', description: 'Pinealon stimulates endogenous serotonin biosynthesis, prospectively allowing attenuated exogenous melatonin doses. Monitor sleep patterns and melatonin sensitivity. Individual variation should be considered.' },
    ],
  },
  {
    productId: 'prod_retatrutide',
    name: 'Retatrutide',
    timingGuidance: 'Administer on the same day each week for consistent hormone regulation. Can be taken with or without food due to subcutaneous administration.',
    halfLifeHours: 144,
    purposeTags: ['Weight Loss', 'Appetite Suppression', 'Glucose Control'],
    purposeWeights: { brain_mood: 35, health_wellness: 85, beauty_antiaging: 30, weight_metabolic: 95, performance_muscle: 40, recovery_longevity: 70 },
    interactions: [
      { withName: 'Metformin', compatibility: 'compatible', description: 'Each of these compounds operate by means of disparate biological routes to improve glucose control and weight management Safe dual protocol tested in medical trials with no pronounced interactions.' },
      { withName: 'SGLT2 Inhibitors', compatibility: 'compatible', description: 'Medical trials included participants on SGLT2 inhibitors with no safety concerns. Reciprocally favorable biological routes for glucose control.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'Disparate treatment-oriented targets.; safe dual protocol. BPC-157 may provide GI protective benefits during Retatrutide use. BPC-157 drives histological repair via proliferative factors while Retatrutide targets metabolic endocrine signal receptors.' },
      { withName: 'NAD+', withProductId: 'prod_nad', compatibility: 'compatible', description: 'Evidence indicates that safe dual protocol - disparate cell-based systems. When these are paired, nAD+ has prospective to support metabolic adaptation during weight loss. Retatrutide targets endocrine signal binding sites (GLP-1/GIP/glucagon) while NAD+ underpins cell-based bioenergetic, coupled with DNA repair.' },
      { withName: 'Oral Contraceptives', compatibility: 'neutral', description: 'When these are paired, space oral contraceptives by 1 hour before retatrutide injection due to delayed gastric emptying impacts.' },
      { withName: 'Tirzepatide', withProductId: 'prod_tirzepatide', compatibility: 'incompatible', description: 'And unpredictable endocrine signal interactions, do not combine with other dual/triple agonists - concern of severe hypoglycemia, excessive gastrointestinal impacts.' },
      { withName: 'Cagrilintide', withProductId: 'prod_cagrilintide', compatibility: 'incompatible', description: 'Retatrutide (triple agonist) and Cagrilintide (amylin agonist) have different biological routes however compounded GI side impacts create substantial concern. Not suggested without specialist supervision. Timing of administration may matter. In terms of co-administration, each of these compounds cause significant GI impacts (gastroparesis, nausea).' },
      { withName: 'Semaglutide', withProductId: 'prod_semaglutide', compatibility: 'incompatible', description: 'Overlapping biological routes boost concern of severe hypoglycemia and excessive side impacts; do not combine with other glp-1 agonists.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Has prospective to substantially reduce insulin requirements due to bolstered glucose control - monitor circulatory glucose closely and adjust insulin doses accordingly.' },
      { withName: 'Warfarin', compatibility: 'incompatible', description: 'Monitor inr more frequently and adjust anticoagulation as needed; weight loss has potential to modulate warfarin requirements.' },
    ],
  },
  {
    productId: 'prod_selank',
    name: 'Selank',
    timingGuidance: 'Nasal Selank works fastest when administered on empty nasal passages. Morning use provides cognitive benefits, while as-needed use offers rapid anxiety relief.',
    halfLifeHours: 0.08,
    purposeTags: ['Immune System', 'Cognitive Health', 'Stress Relief'],
    purposeWeights: { brain_mood: 90, health_wellness: 55, beauty_antiaging: 10, weight_metabolic: 0, performance_muscle: 0, recovery_longevity: 35 },
    interactions: [
      { withName: 'Semax', withProductId: 'prod_semax', compatibility: 'complementary', description: 'In many cases co-administered for amplified cognitive and anxiolytic impacts; related nootropic peptide.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'When these are paired, no established interactions, reciprocally beneficial biological routes for stress response and neural protection.' },
      { withName: 'Noopept', compatibility: 'compatible', description: 'Each of these compounds enhance BDNF and cognitive role by means of disparate cascades - has prospective to complement each other.' },
      { withName: 'Phenylpiracetam', compatibility: 'compatible', description: 'Selank confers anxiolytic impacts while racetams enhance cognitive stimulation.' },
      { withName: 'Modafinil', compatibility: 'compatible', description: 'Selank attenuates anxiety while modafinil amplifies wakefulness - balanced cognitive enhancement. Timing of administration may matter.' },
      { withName: 'Benzodiazepines', compatibility: 'incompatible', description: 'Medical supervision suggested; analogous gabaergic impacts has prospective to potentiate sedation.' },
      { withName: 'SSRI Antidepressants', compatibility: 'incompatible', description: 'Monitor for serotonin impacts; is capable of be co-administered with ssris for amplified mood regulation.' },
      { withName: 'Alcohol', compatibility: 'incompatible', description: 'Each of these compounds modulate GABA system - dual protocol has prospective to cause excessive sedation or unpredictable impacts.' },
    ],
  },
  {
    productId: 'prod_semaglutide',
    name: 'Semaglutide',
    timingGuidance: 'CRITICAL: Take on completely empty stomach (overnight fast) with ≤4oz plain water only. Wait exactly 30 minutes minimum before any food, drink, or other medications. Timing is essential for absorption.',
    halfLifeHours: 168,
    purposeTags: ['Weight Loss', 'Appetite Suppression', 'Glucose Control'],
    purposeWeights: { brain_mood: 35, health_wellness: 90, beauty_antiaging: 30, weight_metabolic: 95, performance_muscle: 35, recovery_longevity: 70 },
    interactions: [
      { withName: 'Cagrilintide', withProductId: 'prod_cagrilintide', compatibility: 'complementary', description: 'Co-administered as CagriSema in medical trials - amylin analog (cagrilintide) + GLP-1 agonist (semaglutide) for amplified weight loss.' },
      { withName: 'Metformin', compatibility: 'compatible', description: 'Routinely used in tandem for diabetes management; reciprocally beneficial biological routes with good safety profile. Clinical relevance is noteworthy.' },
      { withName: 'Growth Hormone Peptides', compatibility: 'compatible', description: 'No established interactions; disparate biological routes of action and binding site targets.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No contraindications; BPC-157 has potential to serve to with GI side impacts if they occur.' },
      { withName: 'Oral Medications', compatibility: 'neutral', description: 'Delayed gastric emptying has prospective to modulate absorption of oral medications; consider timing adjustments. Timing of administration may matter.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Has potential to boost concern of hypoglycemia when co-administered with insulin; calls for circulatory glucose monitoring and prospective insulin dose adjustment.' },
      { withName: 'Tirzepatide', withProductId: 'prod_tirzepatide', compatibility: 'incompatible', description: 'Each of these compounds are incretin mimetics with overlapping biological routes; concurrent harness heightens side impacts absent additional merit.' },
      { withName: 'Sulfonylureas', compatibility: 'incompatible', description: 'Heightened hypoglycemia concern; has prospective to mandate sulfonylurea dose attenuation when initiating semaglutide.' },
    ],
  },
  {
    productId: 'prod_semax',
    name: 'Semax',
    timingGuidance: 'Morning administration optimizes cognitive benefits throughout the day while avoiding evening alertness that could impact sleep',
    halfLifeHours: 0.08,
    purposeTags: ['Cognitive Health', 'Neurological Support'],
    purposeWeights: { brain_mood: 100, health_wellness: 55, beauty_antiaging: 10, weight_metabolic: 0, performance_muscle: 0, recovery_longevity: 45 },
    interactions: [
      { withName: 'Selank', withProductId: 'prod_selank', compatibility: 'complementary', description: 'Reciprocally beneficial anxiolytic impacts while Semax confers cognitive enhancement.' },
      { withName: 'Choline', compatibility: 'complementary', description: 'Choline supports acetylcholine synthesis, potentially enhancing the cognitive benefits of nootropic peptides.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established unfavorable interactions, each of these compounds backing neuroplasticity by means of disparate biological routes.' },
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'compatible', description: 'From a mechanistic perspective, each of these compounds backing cerebral health and recovery, is capable of be used in tandem for comprehensive neuroprotection.' },
      { withName: 'NA-Semax-Amidate', compatibility: 'incompatible', description: 'Choose one or the other based on desired duration, coupled with potency Do not harness simultaneously.; amplified version of same peptide.' },
      { withName: 'Stimulants', compatibility: 'incompatible', description: 'Research supports that has potential to enhance impacts of stimulants - monitor prudently and reduce stimulant doses when co-administering.' },
      { withName: 'MAO-Inhibitors', compatibility: 'incompatible', description: 'Theoretical concern due to monoamine system impacts - consult healthcare provider before co-administering.' },
    ],
  },
  {
    productId: 'prod_sermorelin',
    name: 'Sermorelin',
    timingGuidance: 'Bedtime administration preferred, ensure clear nasal passages',
    halfLifeHours: 0.25,
    purposeTags: ['Muscle Development', 'Anti-Aging', 'Hormonal Support'],
    purposeWeights: { brain_mood: 25, health_wellness: 65, beauty_antiaging: 55, weight_metabolic: 50, performance_muscle: 75, recovery_longevity: 70 },
    interactions: [
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'complementary', description: 'Excellent dual protocol producing 3-5 fold heightens in GH secretion. GHRH and GHRP operate by means of disparate cascades with proven mutually potentiating impacts in medical studies. Individual variation should be considered.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'Highly potent dual protocol - CJC-1295 confers sustained 6-8 day secretion while sermorelin yields immediate pulsatile impacts. Routinely dosed in tandem in medical protocols. This has implications for protocol design.' },
      { withName: 'GHRP-2', compatibility: 'complementary', description: 'Co-administered GHRH+GHRP-2 produces 54-fold GH heightens compared to 20-fold with GHRH alone. Well-documented mutually potentiating biological route.' },
      { withName: 'Thyroid Hormones', compatibility: 'compatible', description: '6.5% of patients develop hypothyroidism calling for endocrine signal replacement. Essential dual protocol as untreated hypothyroidism prevents sermorelin response.' },
      { withName: 'Octreotide', compatibility: 'incompatible', description: 'Somatostatin analogs in a direct manner block GH secretion by activating inhibitory somatostatin binding sites, completely negating sermorelin treatment-oriented impacts.' },
      { withName: 'Lanreotide', compatibility: 'incompatible', description: 'Another somatostatin analog that inhibits GH secretion by means of direct binding site antagonism, making dual protocol with sermorelin counterproductive.' },
      { withName: 'Prednisone', compatibility: 'incompatible', description: 'Notably, substantial-dose glucocorticoids suppress pituitary GH secretion and reduce GHRH binding site sensitivity. From a mechanistic perspective, calls for dose adjustments and IGF-1 monitoring.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Monitor circulatory glucose and consider insulin dose adjustments during sermorelin therapy. GH antagonizes insulin action by means of IGF-1-mediated impacts.' },
    ],
  },
  {
    productId: 'prod_snap8',
    name: 'SNAP-8',
    timingGuidance: 'Apply SNAP-8 to clean, dry skin before heavier products. Morning application should be followed by sunscreen. Evening application can be layered with retinol on alternate days to minimize irritation.',
    halfLifeHours: 0.05,
    purposeTags: ['Skin Quality', 'Anti-Aging'],
    purposeWeights: { brain_mood: 0, health_wellness: 25, beauty_antiaging: 90, weight_metabolic: 0, performance_muscle: 0, recovery_longevity: 30 },
    interactions: [
      { withName: 'Argireline (Acetyl Hexapeptide-3)', compatibility: 'complementary', description: 'Is capable of be co-administered for amplified impact, that said has potential to be redundant as SNAP-8 is approximately 30% more potent Parent compound of SNAP-8 with same biological route.' },
      { withName: 'Leuphasyl', compatibility: 'complementary', description: 'In terms of co-administration, research reveals mutually potentiating impacts when co-administered at equal concentrations (0.75 mM each), producing 47% total inhibition compared to 38% and 7% independently.' },
      { withName: 'Hyaluronic Acid', compatibility: 'complementary', description: 'In many cases formulated in tandem Excellent dual protocol - hyaluronic acid confers hydration, coupled with plumping impacts while SNAP-8 addresses dynamic wrinkles.' },
      { withName: 'Matrixyl', compatibility: 'complementary', description: 'Routinely co-administered in anti-aging formulations Reciprocally beneficial anti-aging peptides - Matrixyl stimulates collagen biosynthesis while SNAP-8 relaxes muscles. Individual variation should be considered.' },
      { withName: 'GHK-Cu', withProductId: 'prod_ghkcu', compatibility: 'compatible', description: 'Safe to harness in same routine with proper timing Reciprocally beneficial biological routes - SNAP-8 attenuates expression lines while GHK-Cu drives collagen synthesis.' },
      { withName: 'Niacinamide', compatibility: 'compatible', description: 'In terms of co-administration, niacinamide calms and strengthens dermal barrier while SNAP-8 targets expression lines Safe dual protocol that operates well in tandem.' },
      { withName: 'Vitamin C (L-Ascorbic Acid)', compatibility: 'neutral', description: 'Has prospective to interact due to pH differences. Harness Vitamin C in the morning and SNAP-8 at night to steer clear of prospective stability issues and maximize efficacy.' },
      { withName: 'Retinol', compatibility: 'incompatible', description: 'From a mechanistic perspective, introduce slowly or harness at disparate times (SNAP-8 morning, retinol evening) Each of these compounds are potent actives. Clinical relevance is noteworthy. When these are paired, retinol is capable of boost dermal sensitivity and has potential to cause irritation when co-administered.' },
      { withName: 'AHA/BHA Acids', compatibility: 'incompatible', description: 'Acids in morning, peptides in evening; harness at disparate times. Glycolic acid and salicylic acid is capable of destabilize peptides and reduce effectiveness.' },
      { withName: 'Copper Peptides', compatibility: 'incompatible', description: 'Research supports that is capable of be used in tandem however copper peptides co-administered with retinol are not advised. When harnessing each of these compounds SNAP-8, coupled with copper peptides, steer clear of retinol in the same routine.' },
    ],
  },
  {
    productId: 'prod_ss31',
    name: 'SS-31',
    timingGuidance: 'Morning and evening after cleansing',
    halfLifeHours: 3.5,
    purposeTags: ['Cellular Energy', 'Anti-Aging', 'Cardiovascular'],
    purposeWeights: { brain_mood: 40, health_wellness: 85, beauty_antiaging: 55, weight_metabolic: 65, performance_muscle: 70, recovery_longevity: 100 },
    interactions: [
      { withName: 'NAD+', withProductId: 'prod_nad', compatibility: 'complementary', description: 'In terms of co-administration, each of these compounds backing mitochondrial role by means of disparate biological routes - SS-31 protects membranes while NAD+ amplifies bioenergetic biosynthesis.' },
      { withName: 'MOTS-c', withProductId: 'prod_motsc', compatibility: 'complementary', description: 'Mots-c regulates metabolism while ss-31 protects mitochondrial structure; each of these compounds are mitochondrial peptides.' },
      { withName: 'Humanin', compatibility: 'complementary', description: 'Another mitochondrial-derived peptide - has prospective to operate in tandem to protect cell-based role and reduce apoptosis.' },
      { withName: 'GHK-Cu', withProductId: 'prod_ghkcu', compatibility: 'compatible', description: 'Disparate biological routes - GHK-Cu operates on gene expression while SS-31 in a direct manner protects mitochondria.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established interactions - BPC-157 focuses on histological restoration while SS-31 targets cell-based energetics.' },
      { withName: 'Thymosin Beta-4', withProductId: 'prod_thymosin_b4', compatibility: 'compatible', description: 'Each of these compounds have cardioprotective impacts by means of disparate cascades - has potential to be reciprocally favorable.' },
    ],
  },
  {
    productId: 'prod_survodutide',
    name: 'Survodutide',
    timingGuidance: 'Administer once weekly on the same day. Can be taken any time of day regardless of meals. If you miss a dose and it\'s within 3 days, take it. If more than 3 days, skip and resume regular schedule.',
    halfLifeHours: 144,
    purposeTags: ['Weight Loss', 'Cardiovascular', 'Metabolic Health'],
    purposeWeights: { brain_mood: 30, health_wellness: 80, beauty_antiaging: 30, weight_metabolic: 90, performance_muscle: 40, recovery_longevity: 65 },
    interactions: [
      { withName: 'Metformin', compatibility: 'compatible', description: 'No direct interaction. Is capable of be used in tandem as exhibited in Phase 2 trials with type 2 diabetes patients on metformin background therapy.' },
      { withName: 'SGLT2 Inhibitors', compatibility: 'compatible', description: 'Research supports that phase 3 trials allow concurrent harness of SGLT2 inhibitors with appropriate monitoring of glycemic control. From a mechanistic perspective, no established interactions.' },
      { withName: 'Protein', compatibility: 'compatible', description: 'Adequate protein preserves lean mass during the significant weight loss achieved with dual agonist therapy.' },
      { withName: 'Insulin', compatibility: 'neutral', description: 'Notably, start with lower insulin doses and titrate based on glucose monitoring. Has potential to mandate insulin dose adjustment due to bolstered glycemic control.' },
      { withName: 'Oral Contraceptives', compatibility: 'neutral', description: 'Delayed gastric emptying has prospective to modulate absorption. Timing of administration may matter. Take oral contraceptives at least 1 hour before survodutide injection.' },
      { withName: 'Semaglutide/Tirzepatide', compatibility: 'incompatible', description: 'Not suggested absent medical supervision. From a mechanistic perspective, each of these compounds are GLP-1 binding site agonists - co-administering has prospective to lead to excessive GLP-1 activation and heightened gastrointestinal side effects.' },
      { withName: 'Sulfonylureas', compatibility: 'incompatible', description: 'Research supports that concern of hypoglycemia when co-administered. Monitor circulatory glucose closely and consider sulfonylurea dose attenuation if needed. Timing of administration may matter.' },
      { withName: 'Warfarin', compatibility: 'incompatible', description: 'From a mechanistic perspective, monitor INR more frequently when initiating or changing survodutide dose. Has prospective to modulate warfarin absorption due to delayed gastric emptying. Clinical relevance is noteworthy.' },
      { withName: 'Other Glucagon Agonists', compatibility: 'incompatible', description: 'Concern of excessive glucagon binding site activation. Timing of administration may matter. From a mechanistic perspective, do not combine with other glucagon binding site agonists.' },
    ],
  },
  {
    productId: 'prod_tb500',
    name: 'TB-500',
    timingGuidance: 'TB-500 timing is flexible and doesn\'t require empty stomach. For localized injuries, inject as close to the injury site as possible. For systemic effects, standard subcutaneous injection sites work well.',
    halfLifeHours: 5.5,
    purposeTags: ['Recovery', 'Tissue Repair', 'Neurological Support'],
    purposeWeights: { brain_mood: 20, health_wellness: 75, beauty_antiaging: 45, weight_metabolic: 15, performance_muscle: 80, recovery_longevity: 90 },
    interactions: [
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'Reciprocally beneficial recuperative biological routes with amplified histological restoration when used in tandem.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'complementary', description: 'TB-500 histological restoration co-administered with GH-releasing impacts for comprehensive recovery.' },
      { withName: 'IGF-1', compatibility: 'complementary', description: 'Amplified muscular and histological regeneration by means of reciprocally favorable proliferative cascades.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'compatible', description: 'Research supports that tB-500 has potential to enhance histological sensitivity to proliferative endocrine signal impacts.' },
      { withName: 'GHRP-6', compatibility: 'compatible', description: 'Evidence indicates that no established unfavorable interactions, prospective for amplified recovery.' },
      { withName: 'Melanotan II', withProductId: 'prod_melanotan2', compatibility: 'compatible', description: 'Notably, completely disparate binding site families with no cascade overlap. Melanotan ii acts on melanocortin binding sites, no interaction expected - tb-500 drives histological repair via actin regulation.' },
    ],
  },
  {
    productId: 'prod_tesamorelin',
    name: 'Tesamorelin',
    timingGuidance: 'Evening injection aligns with natural growth hormone circadian rhythm. Take after dinner but before bedtime for optimal efficacy.',
    halfLifeHours: 0.53,
    purposeTags: ['Weight Loss', 'Muscle Development', 'Metabolic Health'],
    purposeWeights: { brain_mood: 20, health_wellness: 75, beauty_antiaging: 60, weight_metabolic: 80, performance_muscle: 75, recovery_longevity: 80 },
    interactions: [
      { withName: 'Metformin', compatibility: 'compatible', description: 'No direct interactions chronicled. Has prospective to serve to mitigate glucose intolerance concern associated with Tesamorelin therapy. Clinical relevance is noteworthy.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'incompatible', description: 'Monitor IGF-1 concentrations closely and consider dose adjustments to prevent excessive proliferative endocrine signal elevation. Mutually potentiating GH stimulation possible.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'incompatible', description: 'Each of these compounds stimulate GH secretion by means of disparate mechanisms. This has implications for protocol design. Combined harness may lead to supraphysiological IGF-1 concentrations requiring careful monitoring.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Tesamorelin heightens diabetes concern (3.3-fold). Monitor circulatory glucose closely and adjust insulin doses as needed during treatment.' },
      { withName: 'Prednisone', compatibility: 'incompatible', description: 'Consider boosting steroid doses or harnessing alternative anti-inflammatory response-related therapy. Decreases corticosteroid effectiveness.' },
      { withName: 'Octreotide', compatibility: 'incompatible', description: 'Somatostatin analog in a direct manner blocks GH secretion, completely negating Tesamorelin\'s treatment-oriented impacts.' },
      { withName: 'Growth Hormone', compatibility: 'incompatible', description: 'Evidence indicates that concern of acromegaly and metabolic complications from excessive GH exposure. Evidence indicates that redundant and prospectively dangerous dual protocol.' },
    ],
  },
  {
    productId: 'prod_thymosin_a1',
    name: 'Thymosin Alpha-1',
    timingGuidance: 'Administer nasal Ta1 with clean nasal passages for optimal absorption. Morning and evening dosing provides consistent levels. Avoid immediately after nasal irrigation or during active congestion.',
    halfLifeHours: 2,
    purposeTags: ['Recovery', 'Immune System', 'Anti-Inflammatory'],
    purposeWeights: { brain_mood: 25, health_wellness: 100, beauty_antiaging: 45, weight_metabolic: 20, performance_muscle: 30, recovery_longevity: 85 },
    interactions: [
      { withName: 'Interferon-α', compatibility: 'complementary', description: 'And neutropenia, monitor for heightened fever, fatigue. From a mechanistic perspective, amplified antiviral efficacy in hepatitis treatment with mutually potentiating NK cell activation.' },
      { withName: 'Vaccines', compatibility: 'compatible', description: 'Intended treatment-oriented impact enhancing vaccine immunogenicity, notably favorable in elderly and immunocompromised patients.' },
      { withName: 'Chemotherapy Agents', compatibility: 'compatible', description: 'Protective impacts against cytotoxic bone marrow damage while sustaining standard oncology monitoring protocols.' },
      { withName: 'Immunosuppressive Agents', compatibility: 'incompatible', description: 'Fatal immunological hemolytic anemia and graft rejection documented in hematopoietic stem cell transplant patients. Absolute contraindication in organ transplant recipients.' },
      { withName: 'Corticosteroids', compatibility: 'incompatible', description: 'Pharmacodynamic antagonism as Ta1 blocks steroid-induced thymocyte apoptosis, prospectively attenuating immunosuppressive impacts.' },
    ],
  },
  {
    productId: 'prod_thymosin_b4',
    name: 'Thymosin Beta-4',
    timingGuidance: 'Most effective when started early in the injury/healing process. For cardiac protection, must be given within 6 hours of symptom onset. Can be administered any time of day for chronic conditions.',
    halfLifeHours: 1.5,
    purposeTags: ['Neurological Support', 'Tissue Repair', 'Cardiovascular'],
    purposeWeights: { brain_mood: 25, health_wellness: 80, beauty_antiaging: 50, weight_metabolic: 15, performance_muscle: 75, recovery_longevity: 90 },
    interactions: [
      { withName: 'TB-500', withProductId: 'prod_tb500', compatibility: 'complementary', description: 'Co-administered harness confers full-length peptide merits plus concentrated bioactive impacts for amplified histological restoration. Research supports that tB-500 is the bioactive fragment of Thymosin β4.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'complementary', description: 'Reciprocally favorable recuperative biological routes - Tβ4 drives cell migration and angiogenesis while BPC-157 amplifies gastric protection and systemic recuperative.' },
      { withName: 'Growth Hormone', compatibility: 'compatible', description: 'Each of these compounds promote histological restoration by means of disparate cascades, alongside is capable of be used in tandem safely. No direct interactions chronicled.' },
      { withName: 'IGF-1', compatibility: 'compatible', description: 'Evidence indicates that each of these compounds backing histological regeneration by means of distinct biological routes. Evidence indicates that reciprocally favorable proliferative factor impacts absent direct interaction.' },
      { withName: 'NSAIDs', compatibility: 'neutral', description: 'When these are paired, substantial-dose NSAIDs has potential to interfere with inflammatory response-related processes requisite for Tβ4-mediated recuperative. Consider timing or attenuated NSAID dosing.' },
      { withName: 'Corticosteroids', compatibility: 'incompatible', description: 'Steroids has potential to reduce Thymosin β4 effectiveness by inhibiting inflammation-related responses requisite for peak recuperative.' },
      { withName: 'Anticoagulants', compatibility: 'incompatible', description: 'Tβ4 drives angiogenesis which has potential to modulate bleeding concern. Monitor coagulation parameters when used with warfarin or analogous agents.' },
      { withName: 'Chemotherapy', compatibility: 'incompatible', description: 'In terms of co-administration, steer clear of harness during active chemotherapy treatment. Notably, theoretical concern about driving angiogenesis in cancer patients.' },
    ],
  },
  {
    productId: 'prod_tirzepatide',
    name: 'Tirzepatide',
    timingGuidance: 'Tirzepatide can be injected at any time of day, with or without food. Choose a consistent day of the week for weekly injections to maintain steady levels.',
    halfLifeHours: 120,
    purposeTags: ['Weight Loss', 'Appetite Suppression', 'Cardiovascular'],
    purposeWeights: { brain_mood: 40, health_wellness: 90, beauty_antiaging: 35, weight_metabolic: 100, performance_muscle: 45, recovery_longevity: 75 },
    interactions: [
      { withName: 'Metformin', compatibility: 'complementary', description: 'Research supports that reciprocally beneficial biological routes for diabetes management and weight loss with amplified efficacy.' },
      { withName: 'CJC-1295', withProductId: 'prod_cjc1295_dac', compatibility: 'compatible', description: 'Proliferative endocrine signal backing has prospective to serve to preserve muscular mass during rapid weight loss.' },
      { withName: 'Ipamorelin', withProductId: 'prod_ipamorelin', compatibility: 'compatible', description: 'Has prospective to serve to sustain metabolic rate and muscular preservation during caloric restriction.' },
      { withName: 'BPC-157', withProductId: 'prod_bpc157', compatibility: 'compatible', description: 'No established interactions, has prospective to backing gastrointestinal health and reduce GI side impacts. Timing of administration may matter.' },
      { withName: '5-Amino-1MQ', withProductId: 'prod_5amino1mq', compatibility: 'compatible', description: 'NNMT inhibition has prospective to complement GLP-1 impacts for amplified metabolic optimization.' },
      { withName: 'Vitamin B12', compatibility: 'compatible', description: 'Long-term GIP/GLP-1 agonist use may affect B12 status; monitoring and supplementation can be beneficial.' },
      { withName: 'Semaglutide', withProductId: 'prod_semaglutide', compatibility: 'incompatible', description: 'Each of these compounds are GLP-1 agonists - co-administering heightens hypoglycemia and severe GI side impact concern. Individual variation should be considered.' },
      { withName: 'Liraglutide', compatibility: 'incompatible', description: 'Another GLP-1 agonist - dual therapy contraindicated due to additive impacts. Individual variation should be considered.' },
      { withName: 'Insulin', compatibility: 'incompatible', description: 'Has prospective to mandate pronounced insulin dose attenuation due to bolstered sensitivity and glucose control.' },
    ],
  },
];
