/** Clinic, staff, peptide catalog, protocol templates, and education content. */
import type {
  Clinic,
  EducationArticle,
  PeptideProduct,
  ProtocolTemplate,
  StaffMember,
} from '@beacon/domain';

export const clinic: Clinic = {
  id: 'clinic_solstice',
  name: 'Solstice Wellness',
  tagline: 'Personalized peptide therapy & longevity medicine',
  brandColor: '#6B8052',
  locations: [
    {
      id: 'loc_scottsdale',
      clinicId: 'clinic_solstice',
      name: 'Scottsdale Studio',
      city: 'Scottsdale',
      state: 'AZ',
    },
    {
      id: 'loc_austin',
      clinicId: 'clinic_solstice',
      name: 'Austin Clinic',
      city: 'Austin',
      state: 'TX',
    },
  ],
};

export const staff: StaffMember[] = [
  {
    id: 'staff_reyes',
    clinicId: 'clinic_solstice',
    name: 'Dr. Mara Reyes',
    role: 'clinic_owner',
    credential: 'MD',
    title: 'Medical Director',
    email: 'mara.reyes@solstice.health',
    avatarHue: 162,
    licensedStates: ['AZ', 'TX', 'CA'],
    active: true,
  },
  {
    id: 'staff_okafor',
    clinicId: 'clinic_solstice',
    name: 'Dr. Daniel Okafor',
    role: 'provider',
    credential: 'DO',
    title: 'Physician',
    email: 'daniel.okafor@solstice.health',
    avatarHue: 28,
    licensedStates: ['AZ', 'TX'],
    active: true,
  },
  {
    id: 'staff_lindqvist',
    clinicId: 'clinic_solstice',
    name: 'Priya Lindqvist',
    role: 'rn',
    credential: 'NP',
    title: 'Nurse Practitioner',
    email: 'priya.l@solstice.health',
    avatarHue: 292,
    licensedStates: ['AZ'],
    active: true,
  },
  {
    id: 'staff_gomez',
    clinicId: 'clinic_solstice',
    name: 'Tobias Gomez',
    role: 'medical_assistant',
    credential: 'MA',
    title: 'Medical Assistant',
    email: 'tobias.g@solstice.health',
    avatarHue: 210,
    licensedStates: [],
    active: true,
  },
  {
    id: 'staff_huang',
    clinicId: 'clinic_solstice',
    name: 'Wendy Huang',
    role: 'clinic_admin',
    credential: '',
    title: 'Practice Administrator',
    email: 'wendy.h@solstice.health',
    avatarHue: 340,
    licensedStates: [],
    active: true,
  },
];

export const products: PeptideProduct[] = [
  // ----------------------------- Weight loss -----------------------------
  {
    id: 'prod_semaglutide',
    clinicId: 'clinic_solstice',
    name: 'Semaglutide',
    shortName: 'Semaglutide',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A GLP-1 receptor agonist for weight management — it slows gastric emptying and reduces appetite.',
    whatToExpect: [
      'Appetite is noticeably reduced within the first 1–2 weeks.',
      'Most weight change appears between weeks 4 and 16.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Fatigue', 'Constipation'],
    active: true,
    unitPriceUsd: 320,
  },
  {
    id: 'prod_tirzepatide',
    clinicId: 'clinic_solstice',
    name: 'Tirzepatide',
    shortName: 'Tirzepatide',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 20, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A dual GIP/GLP-1 receptor agonist for weight management, often with stronger appetite effects than semaglutide.',
    whatToExpect: [
      'Appetite suppression begins within the first week.',
      'Dose is titrated every 4 weeks to manage tolerability.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Diarrhea', 'Fatigue'],
    active: true,
    unitPriceUsd: 470,
  },
  {
    id: 'prod_retatrutide',
    clinicId: 'clinic_solstice',
    name: 'Retatrutide',
    shortName: 'Retatrutide',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 15, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A triple GIP/GLP-1/glucagon agonist with strong appetite and metabolic effects for weight management.',
    whatToExpect: [
      'Appetite suppression begins within the first week.',
      'Slow titration limits GI side effects; most loss is weeks 8–24.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Diarrhea', 'Fatigue'],
    active: true,
    unitPriceUsd: 540,
  },
  {
    id: 'prod_cagrilintide',
    clinicId: 'clinic_solstice',
    name: 'Cagrilintide',
    shortName: 'Cagrilintide',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A long-acting amylin analog that increases satiety and slows gastric emptying — pairs well with GLP-1s.',
    whatToExpect: [
      'Fullness after meals increases over the first weeks.',
      'Often stacked with semaglutide for an additive effect.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Constipation'],
    active: true,
    unitPriceUsd: 360,
  },
  {
    id: 'prod_survodutide',
    clinicId: 'clinic_solstice',
    name: 'Survodutide',
    shortName: 'Survodutide',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 12, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A GLP-1/glucagon dual agonist for weight management with added metabolic and cardiovascular interest.',
    whatToExpect: [
      'Appetite drops within the first 1–2 weeks.',
      'Titrated weekly to manage nausea.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Diarrhea'],
    active: true,
    unitPriceUsd: 500,
  },
  {
    id: 'prod_tesamorelin',
    clinicId: 'clinic_solstice',
    name: 'Tesamorelin',
    shortName: 'Tesamorelin',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb: 'A GHRH analog used to reduce visceral adipose tissue and support metabolic health.',
    whatToExpect: [
      'Visceral fat changes are gradual over 12–24 weeks.',
      'Dosed daily at night for best response.',
    ],
    commonSideEffects: ['Injection-site redness', 'Joint stiffness', 'Water retention'],
    active: true,
    unitPriceUsd: 295,
  },
  {
    id: 'prod_aod9604',
    clinicId: 'clinic_solstice',
    name: 'AOD-9604',
    shortName: 'AOD-9604',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A modified GH fragment that promotes lipolysis without affecting blood sugar.',
    whatToExpect: [
      'Best paired with diet and training.',
      'Fat-loss effects are gradual over 8–12 weeks.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild headache'],
    active: true,
    unitPriceUsd: 130,
  },
  {
    id: 'prod_5amino1mq',
    clinicId: 'clinic_solstice',
    name: '5-Amino-1MQ',
    shortName: '5-Amino-1MQ',
    category: 'weight_loss',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'An NNMT inhibitor researched for boosting metabolism and supporting fat loss and body composition.',
    whatToExpect: [
      'Works best alongside resistance training.',
      'Energy and body-composition changes build over weeks.',
    ],
    commonSideEffects: ['Mild nausea', 'Headache'],
    active: true,
    unitPriceUsd: 160,
  },

  // ------------------------------- Recovery ------------------------------
  {
    id: 'prod_bpc157',
    clinicId: 'clinic_solstice',
    name: 'BPC-157',
    shortName: 'BPC-157',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A body-protective peptide supporting soft-tissue recovery, joint comfort, and gut health.',
    whatToExpect: [
      'Recovery and joint comfort changes are gradual over 3–6 weeks.',
      'Often run in cycles with rest periods.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild fatigue', 'Headache'],
    active: true,
    unitPriceUsd: 145,
  },
  {
    id: 'prod_tb500',
    clinicId: 'clinic_solstice',
    name: 'TB-500',
    shortName: 'TB-500',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A thymosin beta-4 fragment paired with BPC-157 to support tissue repair and flexibility.',
    whatToExpect: [
      'Typically dosed twice weekly during a loading phase.',
      'Works synergistically with BPC-157 in recovery stacks.',
    ],
    commonSideEffects: ['Injection-site redness', 'Head-rush', 'Fatigue'],
    active: true,
    unitPriceUsd: 160,
  },
  {
    id: 'prod_cjc_ipa',
    clinicId: 'clinic_solstice',
    name: 'CJC-1295 / Ipamorelin',
    shortName: 'CJC/Ipa',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A growth-hormone secretagogue blend taken at night to support deep sleep, recovery, and body composition.',
    whatToExpect: [
      'Sleep quality often improves within the first 1–2 weeks.',
      'Best taken on an empty stomach before bed.',
    ],
    commonSideEffects: ['Facial flush', 'Vivid dreams', 'Water retention', 'Head-rush'],
    active: true,
    unitPriceUsd: 175,
  },
  {
    id: 'prod_thymosin_a1',
    clinicId: 'clinic_solstice',
    name: 'Thymosin Alpha-1',
    shortName: 'Thymosin α1',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A thymic peptide used to support and modulate immune function during recovery.',
    whatToExpect: [
      'Immune-support benefits build over several weeks.',
      'Typically dosed twice weekly during a cycle.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild fatigue'],
    active: true,
    unitPriceUsd: 180,
  },
  {
    id: 'prod_thymosin_b4',
    clinicId: 'clinic_solstice',
    name: 'Thymosin Beta-4',
    shortName: 'TB-4',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A full-length thymosin beta-4 peptide for tissue repair, flexibility, and vascular health.',
    whatToExpect: [
      'Run in a loading phase, then maintenance.',
      'Pairs well with BPC-157 after injury.',
    ],
    commonSideEffects: ['Injection-site redness', 'Head-rush', 'Fatigue'],
    active: true,
    unitPriceUsd: 200,
  },
  {
    id: 'prod_ll37',
    clinicId: 'clinic_solstice',
    name: 'LL-37',
    shortName: 'LL-37',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'An antimicrobial peptide used in short courses to support tissue repair and natural defenses.',
    whatToExpect: [
      'Run in short, defined courses rather than continuously.',
      'Injection-site reactions are usually mild.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild flushing'],
    active: true,
    unitPriceUsd: 170,
  },
  {
    id: 'prod_kpv',
    clinicId: 'clinic_solstice',
    name: 'KPV',
    shortName: 'KPV',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'An anti-inflammatory peptide used to calm gut and systemic inflammation, often with BPC-157.',
    whatToExpect: [
      'Gut-comfort changes are gradual over 3–6 weeks.',
      'Often run in cycles with rest periods.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild headache'],
    active: true,
    unitPriceUsd: 150,
  },
  {
    id: 'prod_pegmgf',
    clinicId: 'clinic_solstice',
    name: 'PEG-MGF',
    shortName: 'PEG-MGF',
    category: 'recovery',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A pegylated mechano growth factor used to support muscle repair after training or injury.',
    whatToExpect: [
      'Dosed a few times weekly, often post-workout.',
      'Pairs with BPC-157 or IGF-1 for repair stacks.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild fatigue'],
    active: true,
    unitPriceUsd: 165,
  },

  // ------------------------------ Aesthetics -----------------------------
  {
    id: 'prod_ghkcu',
    clinicId: 'clinic_solstice',
    name: 'GHK-Cu',
    shortName: 'GHK-Cu',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 5,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A copper peptide supporting skin firmness, collagen, and hair quality.',
    whatToExpect: [
      'Skin tone and texture changes are gradual over 6–10 weeks.',
      'Best paired with consistent sun protection.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild itching'],
    active: true,
    unitPriceUsd: 155,
  },
  {
    id: 'prod_melanotan2',
    clinicId: 'clinic_solstice',
    name: 'Melanotan II',
    shortName: 'Melanotan II',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A melanocortin peptide used to support skin pigmentation during a loading-then-maintenance schedule.',
    whatToExpect: [
      'Loading phase uses small daily doses; then maintenance.',
      'Nausea and flushing are common early and usually ease.',
    ],
    commonSideEffects: ['Nausea', 'Flushing', 'Darkening of moles'],
    active: true,
    unitPriceUsd: 120,
  },
  {
    id: 'prod_melanotan1',
    clinicId: 'clinic_solstice',
    name: 'Melanotan I',
    shortName: 'Melanotan I',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A melanocortin peptide for tanning support with a gentler side-effect profile than MT-II.',
    whatToExpect: [
      'Dosed daily during a short loading phase.',
      'Still requires normal sun protection.',
    ],
    commonSideEffects: ['Flushing', 'Mild nausea', 'Freckling'],
    active: true,
    unitPriceUsd: 120,
  },
  {
    id: 'prod_snap8',
    clinicId: 'clinic_solstice',
    name: 'SNAP-8',
    shortName: 'SNAP-8',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'An octapeptide researched to soften expression lines by relaxing facial micro-contractions.',
    whatToExpect: [
      'Smoothing of fine lines builds gradually.',
      'Often paired with GHK-Cu for skin quality.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild irritation'],
    active: true,
    unitPriceUsd: 140,
  },
  {
    id: 'prod_glutathione',
    clinicId: 'clinic_solstice',
    name: 'Glutathione',
    shortName: 'Glutathione',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 600, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb: 'A master antioxidant used to support skin brightness, oxidative balance, and detox pathways.',
    whatToExpect: [
      'Skin-brightness changes are gradual over several weeks.',
      'Dosed 1–3 times weekly.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild cramping'],
    active: true,
    unitPriceUsd: 90,
  },
  {
    id: 'prod_ahkcu',
    clinicId: 'clinic_solstice',
    name: 'AHK-Cu',
    shortName: 'AHK-Cu',
    category: 'aesthetics',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 5,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A copper tripeptide researched to support hair growth, follicle health, and skin quality.',
    whatToExpect: [
      'Hair and skin changes are gradual over 8–12 weeks.',
      'Often paired with GHK-Cu.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild itching'],
    active: true,
    unitPriceUsd: 150,
  },

  // ------------------------------ Longevity ------------------------------
  {
    id: 'prod_nad',
    clinicId: 'clinic_solstice',
    name: 'NAD+',
    shortName: 'NAD+',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 100, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb: 'A cellular coenzyme used to support energy metabolism, focus, and healthy aging.',
    whatToExpect: [
      'Inject slowly — rapid dosing can cause flushing or nausea.',
      'Energy and focus benefits build over several weeks.',
    ],
    commonSideEffects: ['Flushing', 'Nausea if injected too fast', 'Cramping'],
    active: true,
    unitPriceUsd: 210,
  },
  {
    id: 'prod_epitalon',
    clinicId: 'clinic_solstice',
    name: 'Epitalon',
    shortName: 'Epitalon',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 5,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A telomerase-supporting peptide run in short cycles to support healthy aging and sleep rhythm.',
    whatToExpect: [
      'Run in short, defined cycles a few times per year.',
      'Sleep quality and rhythm often improve during a cycle.',
    ],
    commonSideEffects: ['Mild drowsiness', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 190,
  },
  {
    id: 'prod_motsc',
    clinicId: 'clinic_solstice',
    name: 'MOTS-c',
    shortName: 'MOTS-c',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A mitochondrial-derived peptide supporting metabolic flexibility, exercise capacity, and energy.',
    whatToExpect: [
      'Often dosed a few times weekly during a cycle.',
      'Energy and exercise tolerance changes build over weeks.',
    ],
    commonSideEffects: ['Fatigue', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 175,
  },
  {
    id: 'prod_ss31',
    clinicId: 'clinic_solstice',
    name: 'SS-31 (Elamipretide)',
    shortName: 'SS-31',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A mitochondria-targeting peptide researched to support cellular energy and cardiovascular health.',
    whatToExpect: [
      'Energy and recovery benefits build over several weeks.',
      'Dosed once daily during a cycle.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild headache'],
    active: true,
    unitPriceUsd: 260,
  },
  {
    id: 'prod_mk677',
    clinicId: 'clinic_solstice',
    name: 'MK-677 (Ibutamoren)',
    shortName: 'MK-677',
    category: 'longevity',
    route: 'oral',
    vialAmount: { value: 25, unit: 'mg' },
    defaultDiluentMl: 0,
    budDays: 365,
    storage: 'Store at room temperature, away from light and moisture.',
    blurb: 'An oral growth-hormone secretagogue supporting sleep, recovery, skin, and healthy aging.',
    whatToExpect: [
      'Improved sleep and appetite within the first weeks.',
      'Mild water retention early is common.',
    ],
    commonSideEffects: ['Increased appetite', 'Water retention', 'Vivid dreams'],
    active: true,
    unitPriceUsd: 120,
  },

  // -------------------------------- Muscle -------------------------------
  {
    id: 'prod_sermorelin',
    clinicId: 'clinic_solstice',
    name: 'Sermorelin',
    shortName: 'Sermorelin',
    category: 'muscle',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A GHRH analog taken nightly to support recovery, lean mass, and body composition.',
    whatToExpect: [
      'Sleep depth often improves within the first 2 weeks.',
      'Best taken at night on an empty stomach.',
    ],
    commonSideEffects: ['Facial flush', 'Injection-site redness', 'Head-rush'],
    active: true,
    unitPriceUsd: 140,
  },
  {
    id: 'prod_ipamorelin',
    clinicId: 'clinic_solstice',
    name: 'Ipamorelin',
    shortName: 'Ipamorelin',
    category: 'muscle',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A selective GH secretagogue for lean recovery with minimal effect on cortisol or appetite.',
    whatToExpect: [
      'Gentle, selective GH pulse with little flushing.',
      'Often dosed once or twice daily.',
    ],
    commonSideEffects: ['Mild head-rush', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 150,
  },
  {
    id: 'prod_cjc1295_dac',
    clinicId: 'clinic_solstice',
    name: 'CJC-1295 with DAC',
    shortName: 'CJC-1295 DAC',
    category: 'muscle',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A long-acting GHRH analog that raises baseline GH/IGF-1, dosed once or twice weekly.',
    whatToExpect: [
      'Steady GH elevation rather than sharp pulses.',
      'Often combined with Ipamorelin.',
    ],
    commonSideEffects: ['Facial flush', 'Water retention', 'Head-rush'],
    active: true,
    unitPriceUsd: 170,
  },
  {
    id: 'prod_igf1lr3',
    clinicId: 'clinic_solstice',
    name: 'IGF-1 LR3',
    shortName: 'IGF-1 LR3',
    category: 'muscle',
    route: 'subcutaneous',
    vialAmount: { value: 1, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb: 'A long-acting IGF-1 analog researched for muscle growth, recovery, and nutrient partitioning.',
    whatToExpect: [
      'Dosed once daily, often post-workout.',
      'Run in short cycles with careful dosing.',
    ],
    commonSideEffects: ['Hypoglycemia if mis-dosed', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 220,
  },
  {
    id: 'prod_hgh',
    clinicId: 'clinic_solstice',
    name: 'HGH (Somatropin)',
    shortName: 'HGH',
    category: 'muscle',
    route: 'subcutaneous',
    vialAmount: { value: 30, unit: 'iu' },
    defaultDiluentMl: 1,
    budDays: 21,
    storage: 'Refrigerate at 36–46°F. Do not freeze. Use within 21 days.',
    blurb: 'Recombinant growth hormone for body composition, recovery, and tissue health at conservative doses.',
    whatToExpect: [
      'Sleep and recovery often improve first.',
      'Body-composition changes build over months.',
    ],
    commonSideEffects: ['Water retention', 'Joint stiffness', 'Numbness/tingling'],
    active: true,
    unitPriceUsd: 320,
  },

  // ------------------------------- Cognitive -----------------------------
  {
    id: 'prod_semax',
    clinicId: 'clinic_solstice',
    name: 'Semax',
    shortName: 'Semax',
    category: 'cognitive',
    route: 'subcutaneous',
    vialAmount: { value: 30, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A neuropeptide researched for focus, memory, and neuroprotection.',
    whatToExpect: [
      'Focus and mental clarity changes are often noticed early.',
      'Dosed once or twice daily during a cycle.',
    ],
    commonSideEffects: ['Mild headache', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 130,
  },
  {
    id: 'prod_selank',
    clinicId: 'clinic_solstice',
    name: 'Selank',
    shortName: 'Selank',
    category: 'cognitive',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'An anxiolytic neuropeptide researched for calm focus, stress resilience, and mood.',
    whatToExpect: [
      'Calming, anti-anxiety effects without sedation.',
      'Often paired with Semax.',
    ],
    commonSideEffects: ['Mild drowsiness', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 140,
  },
  {
    id: 'prod_dihexa',
    clinicId: 'clinic_solstice',
    name: 'Dihexa',
    shortName: 'Dihexa',
    category: 'cognitive',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A potent neurogenic peptide researched for synapse formation, memory, and cognition.',
    whatToExpect: [
      'Cognitive effects build over the course of a cycle.',
      'Used in short, defined cycles.',
    ],
    commonSideEffects: ['Headache', 'Overstimulation if over-dosed'],
    active: true,
    unitPriceUsd: 200,
  },
  {
    id: 'prod_pinealon',
    clinicId: 'clinic_solstice',
    name: 'Pinealon',
    shortName: 'Pinealon',
    category: 'cognitive',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A short peptide bioregulator researched for brain function, sleep rhythm, and neuroprotection.',
    whatToExpect: [
      'Run in short cycles.',
      'Often combined with Epitalon or Semax.',
    ],
    commonSideEffects: ['Mild drowsiness', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 150,
  },
  {
    id: 'prod_dsip',
    clinicId: 'clinic_solstice',
    name: 'DSIP',
    shortName: 'DSIP',
    category: 'cognitive',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'Delta sleep-inducing peptide, researched to support deep sleep and stress recovery.',
    whatToExpect: [
      'Taken before bed to support sleep onset and depth.',
      'Effects on sleep can be felt early.',
    ],
    commonSideEffects: ['Morning grogginess', 'Mild headache'],
    active: true,
    unitPriceUsd: 140,
  },
];

const today = new Date();
const wk = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n * 7);
  return d.toISOString().slice(0, 10);
};

export const protocolTemplates: ProtocolTemplate[] = [
  // =============================== WEIGHT LOSS ==============================
  {
    id: 'tmpl_metabolic_reset',
    clinicId: 'clinic_solstice',
    name: 'Metabolic Reset (Semaglutide)',
    category: 'weight_loss',
    summary: 'A 16-week semaglutide weight-management program with a gentle titration ladder.',
    durationWeeks: 16,
    timesAssigned: 48,
    monitoring: ['Weekly weight', 'Bi-weekly waist circumference', 'Side-effect check-ins'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c', 'Lipid panel'],
    redFlags: ['Persistent vomiting or inability to keep fluids down', 'Severe abdominal pain radiating to the back', 'Signs of dehydration'],
    items: [
      {
        id: 'tmplitem_metabolic_sema',
        productId: 'prod_semaglutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 0.25, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 0.25, unit: 'mg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 0.5, unit: 'mg' } },
          { label: 'Weeks 9–12', startWeek: 9, dose: { value: 1, unit: 'mg' } },
          { label: 'Weeks 13–16', startWeek: 13, dose: { value: 1.7, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly on the same day. Rotate sites. Take with or without food.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_tirzepatide_program',
    clinicId: 'clinic_solstice',
    name: 'Tirzepatide Weight Program',
    category: 'weight_loss',
    summary: 'A 20-week tirzepatide program with 4-week titration steps.',
    durationWeeks: 20,
    timesAssigned: 31,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Allergic reaction'],
    items: [
      {
        id: 'tmplitem_tirz',
        productId: 'prod_tirzepatide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 2.5, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 2.5, unit: 'mg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 5, unit: 'mg' } },
          { label: 'Weeks 9–12', startWeek: 9, dose: { value: 7.5, unit: 'mg' } },
          { label: 'Weeks 13–20', startWeek: 13, dose: { value: 10, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly. Rotate sites between abdomen and thigh.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_reta_advanced',
    clinicId: 'clinic_solstice',
    name: 'Retatrutide Advanced',
    category: 'weight_loss',
    summary: 'A 24-week retatrutide program with slow titration for higher metabolic demand.',
    durationWeeks: 24,
    timesAssigned: 12,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c', 'Lipid panel'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Signs of dehydration'],
    items: [
      {
        id: 'tmplitem_reta',
        productId: 'prod_retatrutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 2, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 2, unit: 'mg' } },
          { label: 'Weeks 5–12', startWeek: 5, dose: { value: 4, unit: 'mg' } },
          { label: 'Weeks 13–24', startWeek: 13, dose: { value: 8, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly. Titrate only when tolerability allows.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_cagrisema',
    clinicId: 'clinic_solstice',
    name: 'CagriSema Dual Stack',
    category: 'weight_loss',
    summary: 'Cagrilintide paired with semaglutide for an additive appetite and satiety effect.',
    durationWeeks: 20,
    timesAssigned: 9,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Signs of dehydration'],
    items: [
      {
        id: 'tmplitem_cagri',
        productId: 'prod_cagrilintide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 0.3, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 0.3, unit: 'mg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 1.2, unit: 'mg' } },
          { label: 'Weeks 9–20', startWeek: 9, dose: { value: 2.4, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly, same day as semaglutide.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_cagrisema_sema',
        productId: 'prod_semaglutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 0.25, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 0.25, unit: 'mg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 0.5, unit: 'mg' } },
          { label: 'Weeks 9–20', startWeek: 9, dose: { value: 1, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly on the same day as cagrilintide.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_survodutide',
    clinicId: 'clinic_solstice',
    name: 'Survodutide Metabolic',
    category: 'weight_loss',
    summary: 'A 20-week GLP-1/glucagon dual-agonist program for weight and metabolic health.',
    durationWeeks: 20,
    timesAssigned: 6,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c', 'Lipid panel'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Signs of dehydration'],
    items: [
      {
        id: 'tmplitem_survo',
        productId: 'prod_survodutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 0.6, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 0.6, unit: 'mg' } },
          { label: 'Weeks 5–12', startWeek: 5, dose: { value: 2, unit: 'mg' } },
          { label: 'Weeks 13–20', startWeek: 13, dose: { value: 4, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly. Titrate to manage nausea.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_visceral_fat',
    clinicId: 'clinic_solstice',
    name: 'Visceral Fat Targeting',
    category: 'weight_loss',
    summary: 'Tesamorelin with AOD-9604 to target visceral and stubborn fat over 16 weeks.',
    durationWeeks: 16,
    timesAssigned: 7,
    monitoring: ['Monthly waist circumference', 'Tolerability review'],
    requiredLabs: ['IGF-1', 'Fasting glucose', 'Lipid panel'],
    redFlags: ['Persistent joint swelling', 'Carpal-tunnel-type symptoms'],
    items: [
      {
        id: 'tmplitem_vf_tesa',
        productId: 'prod_tesamorelin',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily evening dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject once daily in the evening. Rotate abdominal sites.',
        timeOfDay: 'Evening',
      },
      {
        id: 'tmplitem_vf_aod',
        productId: 'prod_aod9604',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily morning dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning on an empty stomach.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_metabolic_boost',
    clinicId: 'clinic_solstice',
    name: 'Non-GLP Metabolic Boost',
    category: 'weight_loss',
    summary: '5-Amino-1MQ with AOD-9604 for patients who prefer a non-GLP-1 fat-loss approach.',
    durationWeeks: 12,
    timesAssigned: 5,
    monitoring: ['Bi-weekly weight', 'Energy & training check-ins'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Persistent nausea', 'Unusual fatigue'],
    items: [
      {
        id: 'tmplitem_mb_5amino',
        productId: 'prod_5amino1mq',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning before training.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_mb_aod',
        productId: 'prod_aod9604',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning on an empty stomach.',
        timeOfDay: 'Morning',
      },
    ],
  },

  // ================================ RECOVERY ===============================
  {
    id: 'tmpl_recovery_stack',
    clinicId: 'clinic_solstice',
    name: 'Recovery Stack (BPC + TB-500)',
    category: 'recovery',
    summary: 'BPC-157 and TB-500 combined for soft-tissue recovery, run in 6-week cycles.',
    durationWeeks: 6,
    timesAssigned: 22,
    monitoring: ['Weekly recovery & pain check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site infection', 'Unexpected swelling'],
    items: [
      {
        id: 'tmplitem_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.25, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.25, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject near the area of concern when practical. Rotate sites.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_tb500',
        productId: 'prod_tb500',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 2.5, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 2.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_sleep_restore',
    clinicId: 'clinic_solstice',
    name: 'Sleep & Restore',
    category: 'recovery',
    summary: 'Nightly CJC-1295/Ipamorelin to support deep sleep and recovery.',
    durationWeeks: 12,
    timesAssigned: 27,
    monitoring: ['Weekly sleep score', 'Monthly body-composition review'],
    requiredLabs: ['IGF-1', 'Comprehensive metabolic panel'],
    redFlags: ['Persistent numbness or tingling', 'Significant water retention'],
    items: [
      {
        id: 'tmplitem_cjc',
        productId: 'prod_cjc_ipa',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 nights on, 2 nights off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject at night on an empty stomach, at least 2 hours after eating.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_gut_repair',
    clinicId: 'clinic_solstice',
    name: 'Gut Repair (BPC + KPV)',
    category: 'recovery',
    summary: 'BPC-157 with KPV to calm gut and systemic inflammation over 8 weeks.',
    durationWeeks: 8,
    timesAssigned: 17,
    monitoring: ['Weekly digestive comfort check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Severe or worsening abdominal pain', 'Blood in stool'],
    items: [
      {
        id: 'tmplitem_gut_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Full course', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject in the morning. Rotate sites around the abdomen.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_gut_kpv',
        productId: 'prod_kpv',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Full course', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject alongside BPC-157 in the morning.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_immune_recovery',
    clinicId: 'clinic_solstice',
    name: 'Immune Recovery (Thymosin α1)',
    category: 'recovery',
    summary: 'A twice-weekly Thymosin Alpha-1 cycle to support immune resilience during recovery.',
    durationWeeks: 8,
    timesAssigned: 15,
    monitoring: ['Symptom & wellness check-ins', 'Injection-site review'],
    requiredLabs: ['Complete blood count'],
    redFlags: ['Persistent fever', 'Unusual or worsening fatigue'],
    items: [
      {
        id: 'tmplitem_thymosin',
        productId: 'prod_thymosin_a1',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 1.5, unit: 'mg' },
        titration: [{ label: 'Maintenance', startWeek: 1, dose: { value: 1.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_tissue_repair',
    clinicId: 'clinic_solstice',
    name: 'Post-Injury Tissue Repair',
    category: 'recovery',
    summary: 'Thymosin Beta-4 with BPC-157 for intensive recovery after injury.',
    durationWeeks: 8,
    timesAssigned: 9,
    monitoring: ['Weekly pain & mobility check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site infection', 'Severe or increasing swelling'],
    items: [
      {
        id: 'tmplitem_tr_tb4',
        productId: 'prod_thymosin_b4',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 5, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4 (loading)', startWeek: 1, dose: { value: 5, unit: 'mg' } },
          { label: 'Weeks 5–8 (maintenance)', startWeek: 5, dose: { value: 2.5, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_tr_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Full course', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily dosing.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject near the area of concern when practical. Rotate sites.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_acute_defense',
    clinicId: 'clinic_solstice',
    name: 'LL-37 Acute Defense',
    category: 'recovery',
    summary: 'A short, defined LL-37 course to support tissue repair and natural defenses.',
    durationWeeks: 4,
    timesAssigned: 4,
    monitoring: ['Daily symptom check-ins during the course'],
    requiredLabs: [],
    redFlags: ['High or persistent fever', 'Shortness of breath'],
    items: [
      {
        id: 'tmplitem_ll37',
        productId: 'prod_ll37',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.1, unit: 'mg' },
        titration: [{ label: 'Course', startWeek: 1, dose: { value: 0.1, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full short course.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject once daily for the defined course, then stop.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_muscle_repair_mgf',
    clinicId: 'clinic_solstice',
    name: 'Muscle Repair (PEG-MGF)',
    category: 'recovery',
    summary: 'PEG-MGF with BPC-157 to accelerate muscle repair after hard training blocks.',
    durationWeeks: 6,
    timesAssigned: 8,
    monitoring: ['Weekly soreness & recovery check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Severe localized swelling', 'Spreading injection-site reaction'],
    items: [
      {
        id: 'tmplitem_mr_mgf',
        productId: 'prod_pegmgf',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly, post-workout.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject into the trained muscle group post-workout.',
        timeOfDay: 'Post-workout',
      },
      {
        id: 'tmplitem_mr_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.25, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.25, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject in the morning. Rotate sites.',
        timeOfDay: 'Morning',
      },
    ],
  },

  // =============================== AESTHETICS ==============================
  {
    id: 'tmpl_skin_collagen',
    clinicId: 'clinic_solstice',
    name: 'Skin & Collagen (GHK-Cu)',
    category: 'aesthetics',
    summary: 'A 10-week GHK-Cu program to support skin firmness, tone, and collagen.',
    durationWeeks: 10,
    timesAssigned: 13,
    monitoring: ['Bi-weekly skin photos', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site reaction', 'Persistent itching or rash'],
    items: [
      {
        id: 'tmplitem_skin_ghk',
        productId: 'prod_ghkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject in the evening. Pair with consistent daytime sun protection.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_tan_glow',
    clinicId: 'clinic_solstice',
    name: 'Melanotan Tan & Glow',
    category: 'aesthetics',
    summary: 'A Melanotan II loading-then-maintenance plan for skin pigmentation.',
    durationWeeks: 8,
    timesAssigned: 6,
    monitoring: ['Weekly skin & mole review', 'Tolerability check-ins'],
    requiredLabs: [],
    redFlags: ['New or changing moles', 'Persistent nausea'],
    items: [
      {
        id: 'tmplitem_mt2',
        productId: 'prod_melanotan2',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.25, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–2 (loading)', startWeek: 1, dose: { value: 0.25, unit: 'mg' } },
          { label: 'Weeks 3+ (maintenance)', startWeek: 3, dose: { value: 0.5, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily loading, then maintenance.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the evening. Get a baseline skin check before starting.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_glow_glutathione',
    clinicId: 'clinic_solstice',
    name: 'Brightening Glow',
    category: 'aesthetics',
    summary: 'Glutathione with GHK-Cu to support skin brightness, tone, and antioxidant balance.',
    durationWeeks: 10,
    timesAssigned: 8,
    monitoring: ['Bi-weekly skin photos', 'Tolerability review'],
    requiredLabs: [],
    redFlags: ['Allergic reaction', 'Persistent injection-site irritation'],
    items: [
      {
        id: 'tmplitem_glow_glut',
        productId: 'prod_glutathione',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 200, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 200, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject twice weekly. Protect solution from light.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_glow_ghk',
        productId: 'prod_ghkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject in the evening. Pair with daytime sun protection.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_hair_restore',
    clinicId: 'clinic_solstice',
    name: 'Hair Restore (GHK-Cu + AHK-Cu)',
    category: 'aesthetics',
    summary: 'Copper peptides to support hair growth, follicle health, and scalp quality.',
    durationWeeks: 12,
    timesAssigned: 7,
    monitoring: ['Monthly scalp photos', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Persistent scalp irritation', 'Spreading reaction'],
    items: [
      {
        id: 'tmplitem_hair_ghk',
        productId: 'prod_ghkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject in the evening. Rotate sites.',
        timeOfDay: 'Evening',
      },
      {
        id: 'tmplitem_hair_ahk',
        productId: 'prod_ahkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 1, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 1, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject alongside GHK-Cu in the evening.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_summer_prep',
    clinicId: 'clinic_solstice',
    name: 'Summer Prep (Melanotan I)',
    category: 'aesthetics',
    summary: 'A gentle Melanotan I loading plan for tanning support with a milder profile.',
    durationWeeks: 6,
    timesAssigned: 4,
    monitoring: ['Weekly skin & mole review'],
    requiredLabs: [],
    redFlags: ['New or changing moles', 'Persistent nausea'],
    items: [
      {
        id: 'tmplitem_mt1',
        productId: 'prod_melanotan1',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Loading', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily during loading.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the evening. Always use normal sun protection.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_antiwrinkle',
    clinicId: 'clinic_solstice',
    name: 'Anti-Wrinkle (SNAP-8 + GHK-Cu)',
    category: 'aesthetics',
    summary: 'SNAP-8 with GHK-Cu to soften expression lines and support skin quality.',
    durationWeeks: 10,
    timesAssigned: 5,
    monitoring: ['Bi-weekly skin photos', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Persistent irritation', 'Allergic reaction'],
    items: [
      {
        id: 'tmplitem_aw_snap8',
        productId: 'prod_snap8',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the evening. Rotate sites.',
        timeOfDay: 'Evening',
      },
      {
        id: 'tmplitem_aw_ghk',
        productId: 'prod_ghkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject alongside SNAP-8 in the evening.',
        timeOfDay: 'Evening',
      },
    ],
  },

  // =============================== LONGEVITY ===============================
  {
    id: 'tmpl_longevity',
    clinicId: 'clinic_solstice',
    name: 'Longevity Foundations (NAD+)',
    category: 'longevity',
    summary: 'Twice-weekly NAD+ to support cellular energy and focus.',
    durationWeeks: 10,
    timesAssigned: 14,
    monitoring: ['Energy & focus check-ins', 'Tolerability review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Chest tightness during injection', 'Severe flushing'],
    items: [
      {
        id: 'tmplitem_nad',
        productId: 'prod_nad',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 25, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–2', startWeek: 1, dose: { value: 15, unit: 'mg' } },
          { label: 'Weeks 3+', startWeek: 3, dose: { value: 25, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject slowly over 30–60 seconds to limit flushing.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_epitalon_cycle',
    clinicId: 'clinic_solstice',
    name: 'Epitalon Renewal Cycle',
    category: 'longevity',
    summary: 'A short, defined epitalon cycle to support sleep rhythm and healthy aging.',
    durationWeeks: 3,
    timesAssigned: 11,
    monitoring: ['Daily sleep check-ins during the cycle'],
    requiredLabs: [],
    redFlags: ['Persistent insomnia', 'Unusual mood changes'],
    items: [
      {
        id: 'tmplitem_epitalon',
        productId: 'prod_epitalon',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 10, unit: 'mg' },
        titration: [{ label: 'Cycle', startWeek: 1, dose: { value: 10, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full cycle.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject once daily for the duration of the cycle, then rest.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_mito_energy',
    clinicId: 'clinic_solstice',
    name: 'Mitochondrial Energy',
    category: 'longevity',
    summary: 'MOTS-c with NAD+ to support metabolic flexibility, energy, and exercise capacity.',
    durationWeeks: 8,
    timesAssigned: 7,
    monitoring: ['Energy & exercise check-ins', 'Tolerability review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Severe fatigue', 'Lightheadedness during exercise'],
    items: [
      {
        id: 'tmplitem_me_motsc',
        productId: 'prod_motsc',
        route: 'subcutaneous',
        frequency: 'every_other_day',
        dose: { value: 5, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Every other day.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning, ideally before training days.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_me_nad',
        productId: 'prod_nad',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 25, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 25, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject slowly over 30–60 seconds to limit flushing.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_cellular_ss31',
    clinicId: 'clinic_solstice',
    name: 'Cellular Energy (SS-31)',
    category: 'longevity',
    summary: 'A daily SS-31 cycle to support mitochondrial function and recovery.',
    durationWeeks: 6,
    timesAssigned: 5,
    monitoring: ['Energy & recovery check-ins', 'Tolerability review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Chest tightness', 'Severe headache'],
    items: [
      {
        id: 'tmplitem_ss31',
        productId: 'prod_ss31',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 10, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 10, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject once daily in the morning.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_gh_longevity',
    clinicId: 'clinic_solstice',
    name: 'GH Longevity (MK-677)',
    category: 'longevity',
    summary: 'A daily oral MK-677 program to support sleep, recovery, and healthy aging.',
    durationWeeks: 12,
    timesAssigned: 10,
    monitoring: ['Sleep & appetite check-ins', 'Monthly provider review'],
    requiredLabs: ['IGF-1', 'Fasting glucose', 'HbA1c'],
    redFlags: ['Significant water retention', 'Elevated fasting glucose'],
    items: [
      {
        id: 'tmplitem_mk677',
        productId: 'prod_mk677',
        route: 'oral',
        frequency: 'daily',
        dose: { value: 25, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 25, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily oral dosing.' },
        reconstitution: { diluentMl: 0, syringeType: 'u100' },
        instructions: 'Take orally once daily, typically before bed. No injection required.',
        timeOfDay: 'Bedtime',
      },
    ],
  },

  // ================================= MUSCLE ================================
  {
    id: 'tmpl_lean_mass',
    clinicId: 'clinic_solstice',
    name: 'Lean Mass (Sermorelin + Ipamorelin)',
    category: 'muscle',
    summary: 'A nightly GH-secretagogue stack to support lean mass, recovery, and sleep.',
    durationWeeks: 12,
    timesAssigned: 21,
    monitoring: ['Weekly sleep score', 'Monthly body-composition review'],
    requiredLabs: ['IGF-1', 'Comprehensive metabolic panel'],
    redFlags: ['Persistent numbness or tingling', 'Significant water retention'],
    items: [
      {
        id: 'tmplitem_lm_sermorelin',
        productId: 'prod_sermorelin',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 0.2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 nights on, 2 nights off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject at night on an empty stomach.',
        timeOfDay: 'Bedtime',
      },
      {
        id: 'tmplitem_lm_ipamorelin',
        productId: 'prod_ipamorelin',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 nights on, 2 nights off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject with sermorelin at night.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_gh_pulse',
    clinicId: 'clinic_solstice',
    name: 'GH Pulse (CJC-1295 DAC + Ipamorelin)',
    category: 'muscle',
    summary: 'A weekly long-acting GHRH with Ipamorelin to raise baseline GH for body composition.',
    durationWeeks: 12,
    timesAssigned: 12,
    monitoring: ['Monthly body-composition review', 'Tolerability check-ins'],
    requiredLabs: ['IGF-1', 'Comprehensive metabolic panel'],
    redFlags: ['Significant water retention', 'Numbness or tingling'],
    items: [
      {
        id: 'tmplitem_ghp_cjcdac',
        productId: 'prod_cjc1295_dac',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 1, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 1, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Bedtime',
      },
      {
        id: 'tmplitem_ghp_ipa',
        productId: 'prod_ipamorelin',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject at night on an empty stomach.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_bulk_igf',
    clinicId: 'clinic_solstice',
    name: 'Bulk Cycle (IGF-1 LR3)',
    category: 'muscle',
    summary: 'A 4-week IGF-1 LR3 cycle to support muscle growth and nutrient partitioning.',
    durationWeeks: 4,
    timesAssigned: 6,
    monitoring: ['Weekly weight & strength check-ins', 'Blood-glucose awareness'],
    requiredLabs: ['Fasting glucose', 'IGF-1'],
    redFlags: ['Hypoglycemia (shakiness, sweating, confusion)', 'Persistent fatigue'],
    items: [
      {
        id: 'tmplitem_igf',
        productId: 'prod_igf1lr3',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.05, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.05, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject post-workout. Have a carbohydrate source available.',
        timeOfDay: 'Post-workout',
      },
    ],
  },
  {
    id: 'tmpl_recomp_hgh',
    clinicId: 'clinic_solstice',
    name: 'Recomp (Low-Dose HGH)',
    category: 'muscle',
    summary: 'A conservative daily HGH program for body recomposition and recovery.',
    durationWeeks: 16,
    timesAssigned: 8,
    monitoring: ['Monthly body-composition review', 'Tolerability check-ins'],
    requiredLabs: ['IGF-1', 'Fasting glucose', 'HbA1c', 'Thyroid panel'],
    redFlags: ['Persistent numbness or tingling', 'Significant water retention', 'Elevated fasting glucose'],
    items: [
      {
        id: 'tmplitem_hgh',
        productId: 'prod_hgh',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 2, unit: 'iu' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 1, unit: 'iu' } },
          { label: 'Weeks 5+', startWeek: 5, dose: { value: 2, unit: 'iu' } },
        ],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject in the morning. Rotate sites. Do not freeze the vial.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_strength_mgf',
    clinicId: 'clinic_solstice',
    name: 'Strength Repair (PEG-MGF + IGF-1)',
    category: 'muscle',
    summary: 'PEG-MGF with IGF-1 LR3 to support strength gains and localized muscle repair.',
    durationWeeks: 6,
    timesAssigned: 5,
    monitoring: ['Weekly strength & soreness check-ins', 'Blood-glucose awareness'],
    requiredLabs: ['Fasting glucose', 'IGF-1'],
    redFlags: ['Hypoglycemia', 'Severe localized swelling'],
    items: [
      {
        id: 'tmplitem_sm_mgf',
        productId: 'prod_pegmgf',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly, post-workout.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject into the trained muscle group post-workout.',
        timeOfDay: 'Post-workout',
      },
      {
        id: 'tmplitem_sm_igf',
        productId: 'prod_igf1lr3',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.05, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.05, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject post-workout. Have a carbohydrate source available.',
        timeOfDay: 'Post-workout',
      },
    ],
  },

  // =============================== COGNITIVE ===============================
  {
    id: 'tmpl_focus_semax',
    clinicId: 'clinic_solstice',
    name: 'Focus & Clarity (Semax)',
    category: 'cognitive',
    summary: 'A daily Semax cycle to support focus, memory, and mental clarity.',
    durationWeeks: 4,
    timesAssigned: 13,
    monitoring: ['Daily focus & mood check-ins'],
    requiredLabs: [],
    redFlags: ['Severe headache', 'Overstimulation or insomnia'],
    items: [
      {
        id: 'tmplitem_semax',
        productId: 'prod_semax',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily during the cycle.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject in the morning to support daytime focus.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_calm_selank',
    clinicId: 'clinic_solstice',
    name: 'Calm Focus (Selank)',
    category: 'cognitive',
    summary: 'A daily Selank cycle to support calm focus, stress resilience, and mood.',
    durationWeeks: 4,
    timesAssigned: 10,
    monitoring: ['Daily mood & stress check-ins'],
    requiredLabs: [],
    redFlags: ['Excessive drowsiness', 'Unusual mood changes'],
    items: [
      {
        id: 'tmplitem_selank',
        productId: 'prod_selank',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.3, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 0.3, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily during the cycle.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning or early afternoon.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_neuro_dihexa',
    clinicId: 'clinic_solstice',
    name: 'Neuro Boost (Dihexa)',
    category: 'cognitive',
    summary: 'A short, potent Dihexa cycle researched for synapse formation and memory.',
    durationWeeks: 4,
    timesAssigned: 4,
    monitoring: ['Daily cognition & sleep check-ins'],
    requiredLabs: [],
    redFlags: ['Severe headache', 'Overstimulation or insomnia'],
    items: [
      {
        id: 'tmplitem_dihexa',
        productId: 'prod_dihexa',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 8, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 8, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning. Use only in short, defined cycles.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_sleep_dsip',
    clinicId: 'clinic_solstice',
    name: 'Deep Sleep (DSIP)',
    category: 'cognitive',
    summary: 'A nightly DSIP plan to support sleep onset, depth, and stress recovery.',
    durationWeeks: 6,
    timesAssigned: 9,
    monitoring: ['Daily sleep check-ins'],
    requiredLabs: [],
    redFlags: ['Persistent morning grogginess', 'Unusual mood changes'],
    items: [
      {
        id: 'tmplitem_dsip',
        productId: 'prod_dsip',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 0.2, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Nightly before bed.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject 30–60 minutes before bed.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_brain_pinealon',
    clinicId: 'clinic_solstice',
    name: 'Brain Renewal (Pinealon + Semax)',
    category: 'cognitive',
    summary: 'Pinealon with Semax in a short cycle to support cognition and neuroprotection.',
    durationWeeks: 3,
    timesAssigned: 5,
    monitoring: ['Daily cognition & mood check-ins'],
    requiredLabs: [],
    redFlags: ['Severe headache', 'Unusual mood changes'],
    items: [
      {
        id: 'tmplitem_bp_pinealon',
        productId: 'prod_pinealon',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 5, unit: 'mg' },
        titration: [{ label: 'Cycle', startWeek: 1, dose: { value: 5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full cycle.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning for the duration of the cycle.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_bp_semax',
        productId: 'prod_semax',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 0.5, unit: 'mg' },
        titration: [{ label: 'Cycle', startWeek: 1, dose: { value: 0.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full cycle.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject alongside Pinealon in the morning.',
        timeOfDay: 'Morning',
      },
    ],
  },
];

export const educationArticles: EducationArticle[] = [
  {
    id: 'edu_reconstitution',
    title: 'How to reconstitute your peptide vial',
    category: 'reconstitution',
    readMinutes: 4,
    hue: 162,
    excerpt: 'A step-by-step walkthrough of mixing bacteriostatic water into a lyophilized vial.',
    body: [
      'Peptides arrive as a freeze-dried (lyophilized) powder that must be mixed with bacteriostatic water before use.',
      'Wipe both the peptide vial and the water vial with an alcohol swab and let them dry.',
      'Draw the exact diluent volume your provider specified, then add it slowly down the inside wall of the vial — never spray it directly onto the powder.',
      'Swirl gently until fully dissolved. Do not shake. The solution should look clear.',
      'Label the vial with the date. Beacon tracks the beyond-use date for you automatically.',
    ],
  },
  {
    id: 'edu_injection',
    title: 'Subcutaneous injection technique',
    category: 'injection',
    readMinutes: 5,
    hue: 28,
    excerpt: 'How to give yourself a comfortable, consistent subcutaneous injection.',
    body: [
      'Wash your hands and gather your supplies: vial, insulin syringe, alcohol swabs, and a sharps container.',
      'Choose a site with a fingertip of pinchable fat — the abdomen and thigh are most common.',
      'Clean the site and let it dry. Pinch the skin gently.',
      'Insert the needle at a 45–90° angle in one smooth motion, then depress the plunger steadily.',
      'Rotate sites every injection — Beacon suggests your next site automatically.',
    ],
  },
  {
    id: 'edu_storage',
    title: 'Storing your peptides safely',
    category: 'storage',
    readMinutes: 3,
    hue: 210,
    excerpt: 'Keep your vials potent with correct refrigeration and light protection.',
    body: [
      'Reconstituted peptides must be refrigerated between 36–46°F.',
      'Keep vials in their box or a drawer — light degrades many peptides.',
      'Never freeze a reconstituted vial; freezing damages the peptide.',
      'Discard a vial once it passes its beyond-use date, even if solution remains.',
    ],
  },
  {
    id: 'edu_glp1_expectations',
    title: 'What to expect on a GLP-1 protocol',
    category: 'protocol',
    readMinutes: 6,
    hue: 292,
    excerpt: 'A realistic timeline of appetite, weight, and side-effect changes.',
    body: [
      'Appetite usually drops within the first week or two.',
      'Most weight change occurs between weeks 4 and 16 as the dose is titrated.',
      'Early nausea is common and typically eases as your body adjusts.',
      'Eat smaller, protein-forward meals and stay well hydrated.',
      'Tell your clinic about side effects early — your dose can be adjusted.',
    ],
  },
  {
    id: 'edu_side_effects',
    title: 'Managing common side effects',
    category: 'lifestyle',
    readMinutes: 4,
    hue: 340,
    excerpt: 'Practical strategies for nausea, fatigue, and injection-site reactions.',
    body: [
      'For nausea: eat slowly, avoid greasy foods, and try ginger or peppermint tea.',
      'For fatigue: prioritize protein, hydration, and consistent sleep.',
      'For injection-site redness: rotate sites and apply a cool compress.',
      'Contact your clinic if a symptom is severe, worsening, or persistent.',
    ],
  },
  {
    id: 'edu_cycling',
    title: 'Why some peptides are cycled',
    category: 'protocol',
    readMinutes: 3,
    hue: 95,
    excerpt: 'Understanding on/off periods and why your schedule has rest days.',
    body: [
      'Some peptides are dosed in cycles — periods of active dosing followed by rest.',
      'Cycling can help maintain responsiveness and give tissues time to adapt.',
      'Your Beacon schedule already builds in your rest days — just follow the plan.',
    ],
  },
];
