/** Clinic, staff, peptide catalog, protocol templates, and education content. */
import type {
  Clinic,
  EducationArticle,
  PeptideProduct,
  ProtocolTemplate,
  StaffMember,
} from '@beacon/domain';

export const clinic: Clinic = {
  id: 'clinic_solstice',
  name: 'Solstice Wellness',
  tagline: 'Personalized peptide therapy & longevity medicine',
  brandColor: '#6B8052',
  locations: [
    {
      id: 'loc_scottsdale',
      clinicId: 'clinic_solstice',
      name: 'Scottsdale Studio',
      city: 'Scottsdale',
      state: 'AZ',
    },
    {
      id: 'loc_austin',
      clinicId: 'clinic_solstice',
      name: 'Austin Clinic',
      city: 'Austin',
      state: 'TX',
    },
  ],
};

export const staff: StaffMember[] = [
  {
    id: 'staff_reyes',
    clinicId: 'clinic_solstice',
    name: 'Dr. Mara Reyes',
    role: 'clinic_owner',
    credential: 'MD',
    title: 'Medical Director',
    email: 'mara.reyes@solstice.health',
    avatarHue: 162,
    licensedStates: ['AZ', 'TX', 'CA'],
    active: true,
  },
  {
    id: 'staff_okafor',
    clinicId: 'clinic_solstice',
    name: 'Dr. Daniel Okafor',
    role: 'provider',
    credential: 'DO',
    title: 'Physician',
    email: 'daniel.okafor@solstice.health',
    avatarHue: 28,
    licensedStates: ['AZ', 'TX'],
    active: true,
  },
  {
    id: 'staff_lindqvist',
    clinicId: 'clinic_solstice',
    name: 'Priya Lindqvist',
    role: 'rn',
    credential: 'NP',
    title: 'Nurse Practitioner',
    email: 'priya.l@solstice.health',
    avatarHue: 292,
    licensedStates: ['AZ'],
    active: true,
  },
  {
    id: 'staff_gomez',
    clinicId: 'clinic_solstice',
    name: 'Tobias Gomez',
    role: 'medical_assistant',
    credential: 'MA',
    title: 'Medical Assistant',
    email: 'tobias.g@solstice.health',
    avatarHue: 210,
    licensedStates: [],
    active: true,
  },
  {
    id: 'staff_huang',
    clinicId: 'clinic_solstice',
    name: 'Wendy Huang',
    role: 'clinic_admin',
    credential: '',
    title: 'Practice Administrator',
    email: 'wendy.h@solstice.health',
    avatarHue: 340,
    licensedStates: [],
    active: true,
  },
];

export const products: PeptideProduct[] = [
  {
    id: 'prod_semaglutide',
    clinicId: 'clinic_solstice',
    name: 'Semaglutide',
    shortName: 'Semaglutide',
    category: 'glp1',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A GLP-1 receptor agonist used for weight management — it slows gastric emptying and reduces appetite.',
    whatToExpect: [
      'Appetite is noticeably reduced within the first 1–2 weeks.',
      'Most weight change appears between weeks 4 and 16.',
      'Nausea is common early and usually settles as the dose stabilizes.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Fatigue', 'Constipation'],
    active: true,
    unitPriceUsd: 320,
  },
  {
    id: 'prod_tirzepatide',
    clinicId: 'clinic_solstice',
    name: 'Tirzepatide',
    shortName: 'Tirzepatide',
    category: 'glp1',
    route: 'subcutaneous',
    vialAmount: { value: 20, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A dual GIP/GLP-1 receptor agonist for weight management, often with stronger appetite effects than semaglutide.',
    whatToExpect: [
      'Appetite suppression begins within the first week.',
      'Dose is titrated upward every 4 weeks to manage tolerability.',
      'Energy may dip during titration steps.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Diarrhea', 'Fatigue'],
    active: true,
    unitPriceUsd: 470,
  },
  {
    id: 'prod_bpc157',
    clinicId: 'clinic_solstice',
    name: 'BPC-157',
    shortName: 'BPC-157',
    category: 'healing',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A body-protective peptide used to support soft-tissue recovery, joint comfort, and gut health.',
    whatToExpect: [
      'Recovery and joint comfort changes are gradual over 3–6 weeks.',
      'Often run in cycles with rest periods.',
      'Injection-site reactions are usually mild.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild fatigue', 'Headache'],
    active: true,
    unitPriceUsd: 145,
  },
  {
    id: 'prod_tb500',
    clinicId: 'clinic_solstice',
    name: 'TB-500',
    shortName: 'TB-500',
    category: 'healing',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A thymosin beta-4 fragment paired with BPC-157 to support tissue repair and flexibility.',
    whatToExpect: [
      'Typically dosed twice weekly during a loading phase.',
      'Works synergistically with BPC-157 in recovery stacks.',
    ],
    commonSideEffects: ['Injection-site redness', 'Head-rush', 'Fatigue'],
    active: true,
    unitPriceUsd: 160,
  },
  {
    id: 'prod_cjc_ipa',
    clinicId: 'clinic_solstice',
    name: 'CJC-1295 / Ipamorelin',
    shortName: 'CJC/Ipa',
    category: 'growth_hormone',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A growth-hormone secretagogue blend taken at night to support deep sleep, recovery, and body composition.',
    whatToExpect: [
      'Sleep quality often improves within the first 1–2 weeks.',
      'Best taken on an empty stomach before bed.',
      'A brief flush after injection is normal.',
    ],
    commonSideEffects: ['Facial flush', 'Vivid dreams', 'Water retention', 'Head-rush'],
    active: true,
    unitPriceUsd: 175,
  },
  {
    id: 'prod_nad',
    clinicId: 'clinic_solstice',
    name: 'NAD+',
    shortName: 'NAD+',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 100, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb:
      'A cellular coenzyme used to support energy metabolism, focus, and healthy aging.',
    whatToExpect: [
      'Inject slowly — rapid dosing can cause flushing or a brief wave of nausea.',
      'Energy and focus benefits build over several weeks.',
    ],
    commonSideEffects: ['Flushing', 'Nausea if injected too fast', 'Cramping'],
    active: true,
    unitPriceUsd: 210,
  },
  {
    id: 'prod_pt141',
    clinicId: 'clinic_solstice',
    name: 'PT-141',
    shortName: 'PT-141',
    category: 'sexual_health',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb: 'A melanocortin peptide used as-needed to support libido and arousal.',
    whatToExpect: [
      'Taken as needed, several hours before intimacy.',
      'Temporary flushing and mild nausea can occur.',
    ],
    commonSideEffects: ['Flushing', 'Nausea', 'Headache'],
    active: true,
    unitPriceUsd: 130,
  },
  {
    id: 'prod_ghkcu',
    clinicId: 'clinic_solstice',
    name: 'GHK-Cu',
    shortName: 'GHK-Cu',
    category: 'cosmetic',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 5,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A copper peptide used to support skin firmness, collagen, and hair quality.',
    whatToExpect: [
      'Skin tone and texture changes are gradual over 6–10 weeks.',
      'Best paired with consistent sun protection.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild itching'],
    active: true,
    unitPriceUsd: 155,
  },
  {
    id: 'prod_retatrutide',
    clinicId: 'clinic_solstice',
    name: 'Retatrutide',
    shortName: 'Retatrutide',
    category: 'glp1',
    route: 'subcutaneous',
    vialAmount: { value: 15, unit: 'mg' },
    defaultDiluentMl: 1,
    budDays: 56,
    storage: 'Refrigerate at 36–46°F. Protect from light. Do not freeze.',
    blurb:
      'A triple GIP/GLP-1/glucagon receptor agonist used for weight management, typically with strong appetite and metabolic effects.',
    whatToExpect: [
      'Appetite suppression begins within the first week.',
      'Dose is titrated slowly to manage GI tolerability.',
      'Most weight change appears between weeks 8 and 24.',
    ],
    commonSideEffects: ['Nausea', 'Reduced appetite', 'Diarrhea', 'Fatigue'],
    active: true,
    unitPriceUsd: 540,
  },
  {
    id: 'prod_sermorelin',
    clinicId: 'clinic_solstice',
    name: 'Sermorelin',
    shortName: 'Sermorelin',
    category: 'growth_hormone',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A growth-hormone-releasing hormone analog taken nightly to support recovery, sleep, and body composition.',
    whatToExpect: [
      'Sleep depth often improves within the first 2 weeks.',
      'Best taken at night on an empty stomach.',
      'Effects on body composition build over 2–3 months.',
    ],
    commonSideEffects: ['Facial flush', 'Injection-site redness', 'Head-rush'],
    active: true,
    unitPriceUsd: 140,
  },
  {
    id: 'prod_tesamorelin',
    clinicId: 'clinic_solstice',
    name: 'Tesamorelin',
    shortName: 'Tesamorelin',
    category: 'growth_hormone',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 21,
    storage: 'Refrigerate. Protect from light. Use within 21 days.',
    blurb:
      'A GHRH analog used to reduce visceral adipose tissue and support metabolic health.',
    whatToExpect: [
      'Visceral fat changes are gradual over 12–24 weeks.',
      'Taken daily at night for best response.',
      'Joint stiffness or fluid retention can occur early.',
    ],
    commonSideEffects: ['Injection-site redness', 'Joint stiffness', 'Water retention'],
    active: true,
    unitPriceUsd: 295,
  },
  {
    id: 'prod_ipamorelin',
    clinicId: 'clinic_solstice',
    name: 'Ipamorelin',
    shortName: 'Ipamorelin',
    category: 'growth_hormone',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A selective growth-hormone secretagogue used for lean recovery with minimal effect on cortisol or appetite.',
    whatToExpect: [
      'Gentle, selective GH pulse with little flushing.',
      'Often dosed once or twice daily.',
      'Recovery and sleep benefits build over several weeks.',
    ],
    commonSideEffects: ['Mild head-rush', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 150,
  },
  {
    id: 'prod_epitalon',
    clinicId: 'clinic_solstice',
    name: 'Epitalon',
    shortName: 'Epitalon',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 50, unit: 'mg' },
    defaultDiluentMl: 5,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A telomerase-supporting peptide run in short cycles to support healthy aging and sleep–wake rhythm.',
    whatToExpect: [
      'Run in short, defined cycles a few times per year.',
      'Sleep quality and rhythm often improve during a cycle.',
    ],
    commonSideEffects: ['Mild drowsiness', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 190,
  },
  {
    id: 'prod_motsc',
    clinicId: 'clinic_solstice',
    name: 'MOTS-c',
    shortName: 'MOTS-c',
    category: 'longevity',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A mitochondrial-derived peptide used to support metabolic flexibility, exercise capacity, and energy.',
    whatToExpect: [
      'Often dosed a few times weekly during a cycle.',
      'Energy and exercise tolerance changes build over weeks.',
    ],
    commonSideEffects: ['Fatigue', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 175,
  },
  {
    id: 'prod_kisspeptin',
    clinicId: 'clinic_solstice',
    name: 'Kisspeptin-10',
    shortName: 'Kisspeptin',
    category: 'sexual_health',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A peptide that stimulates the reproductive hormone axis, used to support libido and hormonal vitality.',
    whatToExpect: [
      'Effects on libido and mood build over several weeks.',
      'Often dosed a few times weekly.',
    ],
    commonSideEffects: ['Flushing', 'Headache', 'Injection-site redness'],
    active: true,
    unitPriceUsd: 165,
  },
  {
    id: 'prod_melanotan2',
    clinicId: 'clinic_solstice',
    name: 'Melanotan II',
    shortName: 'Melanotan II',
    category: 'cosmetic',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A melanocortin peptide used to support skin pigmentation during a loading-then-maintenance schedule.',
    whatToExpect: [
      'Loading phase uses small daily doses; then maintenance.',
      'Nausea and flushing are common early and usually ease.',
      'Sun exposure still requires normal protection.',
    ],
    commonSideEffects: ['Nausea', 'Flushing', 'Darkening of moles'],
    active: true,
    unitPriceUsd: 120,
  },
  {
    id: 'prod_thymosin_a1',
    clinicId: 'clinic_solstice',
    name: 'Thymosin Alpha-1',
    shortName: 'Thymosin α1',
    category: 'immune',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'A thymic peptide used to support and modulate immune function, often run in maintenance cycles.',
    whatToExpect: [
      'Immune-support benefits build over several weeks.',
      'Typically dosed twice weekly during a cycle.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild fatigue'],
    active: true,
    unitPriceUsd: 180,
  },
  {
    id: 'prod_ll37',
    clinicId: 'clinic_solstice',
    name: 'LL-37',
    shortName: 'LL-37',
    category: 'immune',
    route: 'subcutaneous',
    vialAmount: { value: 5, unit: 'mg' },
    defaultDiluentMl: 2,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'An antimicrobial peptide used in short courses to support the body’s natural defenses.',
    whatToExpect: [
      'Run in short, defined courses rather than continuously.',
      'Injection-site reactions are usually mild.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild flushing'],
    active: true,
    unitPriceUsd: 170,
  },
  {
    id: 'prod_kpv',
    clinicId: 'clinic_solstice',
    name: 'KPV',
    shortName: 'KPV',
    category: 'immune',
    route: 'subcutaneous',
    vialAmount: { value: 10, unit: 'mg' },
    defaultDiluentMl: 3,
    budDays: 30,
    storage: 'Refrigerate after reconstitution. Use within 30 days.',
    blurb:
      'An anti-inflammatory peptide used to calm gut and systemic inflammation, often alongside BPC-157.',
    whatToExpect: [
      'Gut-comfort changes are gradual over 3–6 weeks.',
      'Often run in cycles with rest periods.',
    ],
    commonSideEffects: ['Injection-site redness', 'Mild headache'],
    active: true,
    unitPriceUsd: 150,
  },
];

const today = new Date();
const wk = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n * 7);
  return d.toISOString().slice(0, 10);
};

export const protocolTemplates: ProtocolTemplate[] = [
  {
    id: 'tmpl_metabolic_reset',
    clinicId: 'clinic_solstice',
    name: 'Metabolic Reset',
    category: 'glp1',
    summary: 'A 16-week semaglutide weight-management program with a gentle titration ladder.',
    durationWeeks: 16,
    timesAssigned: 48,
    monitoring: ['Weekly weight', 'Bi-weekly waist circumference', 'Side-effect check-ins'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c', 'Lipid panel'],
    redFlags: [
      'Persistent vomiting or inability to keep fluids down',
      'Severe abdominal pain radiating to the back',
      'Signs of dehydration',
    ],
    items: [
      {
        id: 'tmplitem_metabolic_sema',
        productId: 'prod_semaglutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 250, unit: 'mcg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 250, unit: 'mcg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 500, unit: 'mcg' } },
          { label: 'Weeks 9–12', startWeek: 9, dose: { value: 1000, unit: 'mcg' } },
          { label: 'Weeks 13–16', startWeek: 13, dose: { value: 1700, unit: 'mcg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly on the same day. Rotate sites. Take with or without food.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_tirzepatide_program',
    clinicId: 'clinic_solstice',
    name: 'Tirzepatide Weight Program',
    category: 'glp1',
    summary: 'A 20-week tirzepatide program with 4-week titration steps.',
    durationWeeks: 20,
    timesAssigned: 31,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Allergic reaction'],
    items: [
      {
        id: 'tmplitem_tirz',
        productId: 'prod_tirzepatide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 2.5, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 2.5, unit: 'mg' } },
          { label: 'Weeks 5–8', startWeek: 5, dose: { value: 5, unit: 'mg' } },
          { label: 'Weeks 9–12', startWeek: 9, dose: { value: 7.5, unit: 'mg' } },
          { label: 'Weeks 13–20', startWeek: 13, dose: { value: 10, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly. Rotate sites between abdomen and thigh.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_recovery_stack',
    clinicId: 'clinic_solstice',
    name: 'Recovery Stack',
    category: 'healing',
    summary: 'BPC-157 and TB-500 combined for soft-tissue recovery, run in 6-week cycles.',
    durationWeeks: 6,
    timesAssigned: 22,
    monitoring: ['Weekly recovery & pain check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site infection', 'Unexpected swelling'],
    items: [
      {
        id: 'tmplitem_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 250, unit: 'mcg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 250, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject near the area of concern when practical. Rotate sites.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_tb500',
        productId: 'prod_tb500',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 2.5, unit: 'mg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 2.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_sleep_restore',
    clinicId: 'clinic_solstice',
    name: 'Sleep & Restore',
    category: 'growth_hormone',
    summary: 'Nightly CJC-1295/Ipamorelin to support deep sleep and recovery.',
    durationWeeks: 12,
    timesAssigned: 27,
    monitoring: ['Weekly sleep score', 'Monthly body-composition review'],
    requiredLabs: ['IGF-1', 'Comprehensive metabolic panel'],
    redFlags: ['Persistent numbness or tingling', 'Significant water retention'],
    items: [
      {
        id: 'tmplitem_cjc',
        productId: 'prod_cjc_ipa',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 300, unit: 'mcg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 300, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 nights on, 2 nights off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject at night on an empty stomach, at least 2 hours after eating.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_longevity',
    clinicId: 'clinic_solstice',
    name: 'Longevity Foundations',
    category: 'longevity',
    summary: 'Twice-weekly NAD+ to support cellular energy and focus.',
    durationWeeks: 10,
    timesAssigned: 14,
    monitoring: ['Energy & focus check-ins', 'Tolerability review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Chest tightness during injection', 'Severe flushing'],
    items: [
      {
        id: 'tmplitem_nad',
        productId: 'prod_nad',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 25, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–2', startWeek: 1, dose: { value: 15, unit: 'mg' } },
          { label: 'Weeks 3+', startWeek: 3, dose: { value: 25, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject slowly over 30–60 seconds to limit flushing.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_glp1_microdose',
    clinicId: 'clinic_solstice',
    name: 'GLP-1 Microdose Maintenance',
    category: 'glp1',
    summary: 'A low-dose semaglutide maintenance plan for patients holding their goal weight.',
    durationWeeks: 24,
    timesAssigned: 19,
    monitoring: ['Bi-weekly weight', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Unexplained rapid weight loss', 'Persistent vomiting'],
    items: [
      {
        id: 'tmplitem_glp1micro_sema',
        productId: 'prod_semaglutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 250, unit: 'mcg' },
        titration: [{ label: 'Maintenance', startWeek: 1, dose: { value: 250, unit: 'mcg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly on the same day. Rotate sites.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_retatrutide_advanced',
    clinicId: 'clinic_solstice',
    name: 'Retatrutide Advanced Weight',
    category: 'glp1',
    summary: 'A 24-week retatrutide program with slow titration for higher metabolic demand.',
    durationWeeks: 24,
    timesAssigned: 12,
    monitoring: ['Weekly weight', 'Side-effect check-ins', 'Monthly provider review'],
    requiredLabs: ['Comprehensive metabolic panel', 'HbA1c', 'Lipid panel'],
    redFlags: ['Persistent vomiting', 'Severe abdominal pain', 'Signs of dehydration'],
    items: [
      {
        id: 'tmplitem_reta',
        productId: 'prod_retatrutide',
        route: 'subcutaneous',
        frequency: 'weekly',
        dose: { value: 2, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4', startWeek: 1, dose: { value: 2, unit: 'mg' } },
          { label: 'Weeks 5–12', startWeek: 5, dose: { value: 4, unit: 'mg' } },
          { label: 'Weeks 13–24', startWeek: 13, dose: { value: 8, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Continuous weekly dosing.' },
        reconstitution: { diluentMl: 1, syringeType: 'u100' },
        instructions: 'Inject once weekly. Titrate only when tolerability allows.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_gut_repair',
    clinicId: 'clinic_solstice',
    name: 'BPC-157 Gut Repair',
    category: 'healing',
    summary: 'A focused 8-week BPC-157 course to support gut lining and digestive comfort.',
    durationWeeks: 8,
    timesAssigned: 17,
    monitoring: ['Weekly digestive comfort check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Severe or worsening abdominal pain', 'Blood in stool'],
    items: [
      {
        id: 'tmplitem_gutrepair_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 500, unit: 'mcg' },
        titration: [{ label: 'Full course', startWeek: 1, dose: { value: 500, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject in the morning. Rotate sites around the abdomen.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_tissue_repair',
    clinicId: 'clinic_solstice',
    name: 'Post-Injury Tissue Repair',
    category: 'healing',
    summary: 'An intensive 8-week BPC-157 + TB-500 stack for recovery after injury.',
    durationWeeks: 8,
    timesAssigned: 9,
    monitoring: ['Weekly pain & mobility check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site infection', 'Severe or increasing swelling'],
    items: [
      {
        id: 'tmplitem_tissue_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 500, unit: 'mcg' },
        titration: [{ label: 'Full course', startWeek: 1, dose: { value: 500, unit: 'mcg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily dosing.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject near the area of concern when practical. Rotate sites.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_tissue_tb',
        productId: 'prod_tb500',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 5, unit: 'mg' },
        titration: [
          { label: 'Weeks 1–4 (loading)', startWeek: 1, dose: { value: 5, unit: 'mg' } },
          { label: 'Weeks 5–8 (maintenance)', startWeek: 5, dose: { value: 2.5, unit: 'mg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_sermorelin_nightly',
    clinicId: 'clinic_solstice',
    name: 'Sermorelin Nightly',
    category: 'growth_hormone',
    summary: 'A nightly sermorelin program to support recovery, sleep, and body composition.',
    durationWeeks: 12,
    timesAssigned: 21,
    monitoring: ['Weekly sleep score', 'Monthly body-composition review'],
    requiredLabs: ['IGF-1', 'Comprehensive metabolic panel'],
    redFlags: ['Persistent numbness or tingling', 'Significant water retention'],
    items: [
      {
        id: 'tmplitem_sermorelin',
        productId: 'prod_sermorelin',
        route: 'subcutaneous',
        frequency: 'five_on_two_off',
        dose: { value: 200, unit: 'mcg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 200, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 nights on, 2 nights off.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject at night on an empty stomach, at least 2 hours after eating.',
        timeOfDay: 'Bedtime',
      },
    ],
  },
  {
    id: 'tmpl_tesamorelin_visceral',
    clinicId: 'clinic_solstice',
    name: 'Tesamorelin Visceral Fat',
    category: 'growth_hormone',
    summary: 'A daily tesamorelin program targeting visceral fat over 16 weeks.',
    durationWeeks: 16,
    timesAssigned: 8,
    monitoring: ['Monthly waist circumference', 'Tolerability review'],
    requiredLabs: ['IGF-1', 'Fasting glucose', 'Lipid panel'],
    redFlags: ['Persistent joint swelling', 'Carpal-tunnel-type symptoms'],
    items: [
      {
        id: 'tmplitem_tesamorelin',
        productId: 'prod_tesamorelin',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily evening dosing.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject once daily in the evening. Rotate abdominal sites.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_epitalon_cycle',
    clinicId: 'clinic_solstice',
    name: 'Epitalon Renewal Cycle',
    category: 'longevity',
    summary: 'A short, defined epitalon cycle to support sleep rhythm and healthy aging.',
    durationWeeks: 3,
    timesAssigned: 11,
    monitoring: ['Daily sleep check-ins during the cycle'],
    requiredLabs: [],
    redFlags: ['Persistent insomnia', 'Unusual mood changes'],
    items: [
      {
        id: 'tmplitem_epitalon',
        productId: 'prod_epitalon',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 10, unit: 'mg' },
        titration: [{ label: 'Cycle', startWeek: 1, dose: { value: 10, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full cycle.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject once daily for the duration of the cycle, then rest.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_motsc_metabolic',
    clinicId: 'clinic_solstice',
    name: 'MOTS-c Metabolic',
    category: 'longevity',
    summary: 'Thrice-weekly MOTS-c to support metabolic flexibility and exercise capacity.',
    durationWeeks: 8,
    timesAssigned: 7,
    monitoring: ['Energy & exercise check-ins', 'Tolerability review'],
    requiredLabs: ['Comprehensive metabolic panel'],
    redFlags: ['Severe fatigue', 'Lightheadedness during exercise'],
    items: [
      {
        id: 'tmplitem_motsc',
        productId: 'prod_motsc',
        route: 'subcutaneous',
        frequency: 'every_other_day',
        dose: { value: 5, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Every other day.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the morning, ideally before training days.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_pt141_asneeded',
    clinicId: 'clinic_solstice',
    name: 'PT-141 As-Needed',
    category: 'sexual_health',
    summary: 'An as-needed PT-141 plan for libido and arousal support.',
    durationWeeks: 12,
    timesAssigned: 16,
    monitoring: ['Tolerability check-ins', 'Blood-pressure note if flushing occurs'],
    requiredLabs: [],
    redFlags: ['Severe or prolonged headache', 'Chest pain', 'Fainting'],
    items: [
      {
        id: 'tmplitem_pt141',
        productId: 'prod_pt141',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 1, unit: 'mg' },
        titration: [{ label: 'As needed', startWeek: 1, dose: { value: 1, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Use as needed, not more than twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject several hours before intimacy. Do not exceed twice weekly.',
        timeOfDay: 'As needed',
      },
    ],
  },
  {
    id: 'tmpl_kisspeptin_vitality',
    clinicId: 'clinic_solstice',
    name: 'Kisspeptin Vitality',
    category: 'sexual_health',
    summary: 'A twice-weekly kisspeptin program to support libido and hormonal vitality.',
    durationWeeks: 10,
    timesAssigned: 6,
    monitoring: ['Libido & mood check-ins', 'Tolerability review'],
    requiredLabs: ['Total testosterone', 'LH / FSH'],
    redFlags: ['Severe headache', 'Persistent flushing'],
    items: [
      {
        id: 'tmplitem_kisspeptin',
        productId: 'prod_kisspeptin',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 1, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 1, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_skin_collagen',
    clinicId: 'clinic_solstice',
    name: 'GHK-Cu Skin & Collagen',
    category: 'cosmetic',
    summary: 'A 10-week GHK-Cu program to support skin firmness, tone, and collagen.',
    durationWeeks: 10,
    timesAssigned: 13,
    monitoring: ['Bi-weekly skin photos', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Spreading injection-site reaction', 'Persistent itching or rash'],
    items: [
      {
        id: 'tmplitem_skin_ghk',
        productId: 'prod_ghkcu',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 2, unit: 'mg' },
        titration: [{ label: 'Full program', startWeek: 1, dose: { value: 2, unit: 'mg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 5, syringeType: 'u100' },
        instructions: 'Inject in the evening. Pair with consistent daytime sun protection.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_tan_glow',
    clinicId: 'clinic_solstice',
    name: 'Melanotan Tan & Glow',
    category: 'cosmetic',
    summary: 'A Melanotan II loading-then-maintenance plan for skin pigmentation.',
    durationWeeks: 8,
    timesAssigned: 5,
    monitoring: ['Weekly skin & mole review', 'Tolerability check-ins'],
    requiredLabs: [],
    redFlags: ['New or changing moles', 'Persistent nausea'],
    items: [
      {
        id: 'tmplitem_mt2',
        productId: 'prod_melanotan2',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 250, unit: 'mcg' },
        titration: [
          { label: 'Weeks 1–2 (loading)', startWeek: 1, dose: { value: 250, unit: 'mcg' } },
          { label: 'Weeks 3+ (maintenance)', startWeek: 3, dose: { value: 500, unit: 'mcg' } },
        ],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily loading, then 2–3× weekly maintenance.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject in the evening. Get a baseline skin check before starting.',
        timeOfDay: 'Evening',
      },
    ],
  },
  {
    id: 'tmpl_immune_resilience',
    clinicId: 'clinic_solstice',
    name: 'Immune Resilience',
    category: 'immune',
    summary: 'A twice-weekly Thymosin Alpha-1 maintenance cycle to support immune function.',
    durationWeeks: 8,
    timesAssigned: 15,
    monitoring: ['Symptom & wellness check-ins', 'Injection-site review'],
    requiredLabs: ['Complete blood count'],
    redFlags: ['Persistent fever', 'Unusual or worsening fatigue'],
    items: [
      {
        id: 'tmplitem_thymosin',
        productId: 'prod_thymosin_a1',
        route: 'subcutaneous',
        frequency: 'twice_weekly',
        dose: { value: 1.5, unit: 'mg' },
        titration: [{ label: 'Maintenance', startWeek: 1, dose: { value: 1.5, unit: 'mg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Twice weekly.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject twice weekly, spaced 3–4 days apart.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_acute_defense',
    clinicId: 'clinic_solstice',
    name: 'LL-37 Acute Defense',
    category: 'immune',
    summary: 'A short, defined LL-37 course to support the body’s natural defenses.',
    durationWeeks: 4,
    timesAssigned: 4,
    monitoring: ['Daily symptom check-ins during the course'],
    requiredLabs: [],
    redFlags: ['High or persistent fever', 'Shortness of breath'],
    items: [
      {
        id: 'tmplitem_ll37',
        productId: 'prod_ll37',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 100, unit: 'mcg' },
        titration: [{ label: 'Course', startWeek: 1, dose: { value: 100, unit: 'mcg' } }],
        cycle: { enabled: false, onDays: 0, offDays: 0, description: 'Daily for the full short course.' },
        reconstitution: { diluentMl: 2, syringeType: 'u100' },
        instructions: 'Inject once daily for the defined course, then stop.',
        timeOfDay: 'Morning',
      },
    ],
  },
  {
    id: 'tmpl_gut_calm',
    clinicId: 'clinic_solstice',
    name: 'KPV Gut Calm',
    category: 'immune',
    summary: 'A 6-week KPV + BPC-157 stack to calm gut and systemic inflammation.',
    durationWeeks: 6,
    timesAssigned: 8,
    monitoring: ['Weekly digestive comfort check-ins', 'Injection-site review'],
    requiredLabs: [],
    redFlags: ['Severe abdominal pain', 'Blood in stool'],
    items: [
      {
        id: 'tmplitem_gutcalm_kpv',
        productId: 'prod_kpv',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 500, unit: 'mcg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 500, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject in the morning. Rotate sites around the abdomen.',
        timeOfDay: 'Morning',
      },
      {
        id: 'tmplitem_gutcalm_bpc',
        productId: 'prod_bpc157',
        route: 'subcutaneous',
        frequency: 'daily',
        dose: { value: 250, unit: 'mcg' },
        titration: [{ label: 'Full cycle', startWeek: 1, dose: { value: 250, unit: 'mcg' } }],
        cycle: { enabled: true, onDays: 5, offDays: 2, description: '5 days on, 2 days off each week.' },
        reconstitution: { diluentMl: 3, syringeType: 'u100' },
        instructions: 'Inject alongside KPV in the morning.',
        timeOfDay: 'Morning',
      },
    ],
  },
];

export const educationArticles: EducationArticle[] = [
  {
    id: 'edu_reconstitution',
    title: 'How to reconstitute your peptide vial',
    category: 'reconstitution',
    readMinutes: 4,
    hue: 162,
    excerpt: 'A step-by-step walkthrough of mixing bacteriostatic water into a lyophilized vial.',
    body: [
      'Peptides arrive as a freeze-dried (lyophilized) powder that must be mixed with bacteriostatic water before use.',
      'Wipe both the peptide vial and the water vial with an alcohol swab and let them dry.',
      'Draw the exact diluent volume your provider specified, then add it slowly down the inside wall of the vial — never spray it directly onto the powder.',
      'Swirl gently until fully dissolved. Do not shake. The solution should look clear.',
      'Label the vial with the date. Beacon tracks the beyond-use date for you automatically.',
    ],
  },
  {
    id: 'edu_injection',
    title: 'Subcutaneous injection technique',
    category: 'injection',
    readMinutes: 5,
    hue: 28,
    excerpt: 'How to give yourself a comfortable, consistent subcutaneous injection.',
    body: [
      'Wash your hands and gather your supplies: vial, insulin syringe, alcohol swabs, and a sharps container.',
      'Choose a site with a fingertip of pinchable fat — the abdomen and thigh are most common.',
      'Clean the site and let it dry. Pinch the skin gently.',
      'Insert the needle at a 45–90° angle in one smooth motion, then depress the plunger steadily.',
      'Rotate sites every injection — Beacon suggests your next site automatically.',
    ],
  },
  {
    id: 'edu_storage',
    title: 'Storing your peptides safely',
    category: 'storage',
    readMinutes: 3,
    hue: 210,
    excerpt: 'Keep your vials potent with correct refrigeration and light protection.',
    body: [
      'Reconstituted peptides must be refrigerated between 36–46°F.',
      'Keep vials in their box or a drawer — light degrades many peptides.',
      'Never freeze a reconstituted vial; freezing damages the peptide.',
      'Discard a vial once it passes its beyond-use date, even if solution remains.',
    ],
  },
  {
    id: 'edu_glp1_expectations',
    title: 'What to expect on a GLP-1 protocol',
    category: 'protocol',
    readMinutes: 6,
    hue: 292,
    excerpt: 'A realistic timeline of appetite, weight, and side-effect changes.',
    body: [
      'Appetite usually drops within the first week or two.',
      'Most weight change occurs between weeks 4 and 16 as the dose is titrated.',
      'Early nausea is common and typically eases as your body adjusts.',
      'Eat smaller, protein-forward meals and stay well hydrated.',
      'Tell your clinic about side effects early — your dose can be adjusted.',
    ],
  },
  {
    id: 'edu_side_effects',
    title: 'Managing common side effects',
    category: 'lifestyle',
    readMinutes: 4,
    hue: 340,
    excerpt: 'Practical strategies for nausea, fatigue, and injection-site reactions.',
    body: [
      'For nausea: eat slowly, avoid greasy foods, and try ginger or peppermint tea.',
      'For fatigue: prioritize protein, hydration, and consistent sleep.',
      'For injection-site redness: rotate sites and apply a cool compress.',
      'Contact your clinic if a symptom is severe, worsening, or persistent.',
    ],
  },
  {
    id: 'edu_cycling',
    title: 'Why some peptides are cycled',
    category: 'protocol',
    readMinutes: 3,
    hue: 95,
    excerpt: 'Understanding on/off periods and why your schedule has rest days.',
    body: [
      'Some peptides are dosed in cycles — periods of active dosing followed by rest.',
      'Cycling can help maintain responsiveness and give tissues time to adapt.',
      'Your Beacon schedule already builds in your rest days — just follow the plan.',
    ],
  },
];
